package com.njpes.www.entity.baseinfo.organization;

import java.io.Serializable;

public class Ecpsychicjob implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column ec_psychicjob.id
     *
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column ec_psychicjob.rwmc
     *
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    private String rwmc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column ec_psychicjob.ecid
     *
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    private Long ecid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column ec_psychicjob.rwjl
     *
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    private String rwjl;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column ec_psychicjob.id
     *
     * @return the value of ec_psychicjob.id
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column ec_psychicjob.id
     *
     * @param id
     *            the value for ec_psychicjob.id
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column ec_psychicjob.rwmc
     *
     * @return the value of ec_psychicjob.rwmc
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public String getRwmc() {
        return rwmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column ec_psychicjob.rwmc
     *
     * @param rwmc
     *            the value for ec_psychicjob.rwmc
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public void setRwmc(String rwmc) {
        this.rwmc = rwmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column ec_psychicjob.ecid
     *
     * @return the value of ec_psychicjob.ecid
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public Long getEcid() {
        return ecid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column ec_psychicjob.ecid
     *
     * @param ecid
     *            the value for ec_psychicjob.ecid
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public void setEcid(Long ecid) {
        this.ecid = ecid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column ec_psychicjob.rwjl
     *
     * @return the value of ec_psychicjob.rwjl
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public String getRwjl() {
        return rwjl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column ec_psychicjob.rwjl
     *
     * @param rwjl
     *            the value for ec_psychicjob.rwjl
     * @mbggenerated Sat May 09 22:28:55 CST 2015
     */
    public void setRwjl(String rwjl) {
        this.rwjl = rwjl;
    }
}