package com.njpes.www.entity.baseinfo.organization;

import java.io.Serializable;

import com.njpes.www.constant.Constants;
import com.njpes.www.entity.baseinfo.enums.OrganizationType;

public class Organization implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.id
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.code
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.name
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.parent_id
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.parent_ids
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.org_type
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private String orgType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.org_level
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private Integer orgLevel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column organization.sort
     *
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    private Integer sort;

    private Integer isshow;

    private String provinceid;

    private String cityid;

    private String countyid;

    private String townid;

    private String locked;

    private String provincename;

    private String cityname;

    private String townname;

    private String countyname;

    private String imageurl;

    private String introduce;

    public String getImageurl() {
        return imageurl;
    }

    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public String getProvincename() {
        return provincename;
    }

    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    public String getCityname() {
        return cityname;
    }

    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    public String getTownname() {
        return townname;
    }

    public void setTownname(String townname) {
        this.townname = townname;
    }

    public String getCountyname() {
        return countyname;
    }

    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    public String getLocked() {
        return locked;
    }

    public void setLocked(String locked) {
        this.locked = locked;
    }

    public String getTownid() {
        return townid;
    }

    public void setTownid(String townid) {
        this.townid = townid;
    }

    public String getProvinceid() {
        return provinceid;
    }

    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    public String getCityid() {
        return cityid;
    }

    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    public String getCountyid() {
        return countyid;
    }

    public void setCountyid(String countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.id
     *
     * @return the value of organization.id
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.id
     *
     * @param id
     *            the value for organization.id
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.code
     *
     * @return the value of organization.code
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.code
     *
     * @param code
     *            the value for organization.code
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.name
     *
     * @return the value of organization.name
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.name
     *
     * @param name
     *            the value for organization.name
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.parent_id
     *
     * @return the value of organization.parent_id
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.parent_id
     *
     * @param parentId
     *            the value for organization.parent_id
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.parent_ids
     *
     * @return the value of organization.parent_ids
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.parent_ids
     *
     * @param parentIds
     *            the value for organization.parent_ids
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.org_type
     *
     * @return the value of organization.org_type
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.org_type
     *
     * @param orgType
     *            the value for organization.org_type
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.org_level
     *
     * @return the value of organization.org_level
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public Integer getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.org_level
     *
     * @param orgLevel
     *            the value for organization.org_level
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setOrgLevel(Integer orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column organization.sort
     *
     * @return the value of organization.sort
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column organization.sort
     *
     * @param sort
     *            the value for organization.sort
     * @mbggenerated Sat May 09 20:41:44 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Integer getIsshow() {
        return isshow;
    }

    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * 判断组织机构id是否为陶老师工作站 包含判断分站
     */
    public boolean isTaoLaoShiStation(Organization org) {
        if (org.getId().equals(Constants.TAOLAOSHI_STATION)) {
            return true;
        } else if (org.getParentIds().startsWith("0/" + Constants.TAOLAOSHI_STATION + "/")) {
            return true;
        }
        return false;
    }

    /**
     * 返回组织机构类型
     * 
     * @return 返回参见com.njpes.www.entity.baseinfo.enums.OrganizationType
     * @author 赵忠诚
     */
    public OrganizationType returnOrgTypeEnum() {
        if (getOrgType().equals(OrganizationType.school.getId())) {
            return OrganizationType.school;
        } else if (getOrgType().equals(OrganizationType.ec.getId())) {
            return OrganizationType.ec;
        } else if (getOrgType().equals(OrganizationType.taoststion.getId())) {
            return OrganizationType.taoststion;
        } else {
            return null;
        }
    }
}