package com.njpes.www.entity.baseinfo.organization;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import com.njpes.www.entity.baseinfo.enums.SchoolBXLX;
import com.njpes.www.entity.baseinfo.enums.XueDuan;

public class School implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 144400451959559941L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.id
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxdm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxdm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxmc
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxmc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxywmc
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxywmc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxdz
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxdz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxyzbm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxyzbm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xzqhm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xzqhm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.jxny
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String jxny;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xqr
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xqr;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxbxlxm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxbxlxm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxjbzm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxjbzm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxzgbmm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxzgbmm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.fddbrh
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String fddbrh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.frzsh
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String frzsh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xzgh
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xzgh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xzxm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xzxm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.dwfzrh
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String dwfzrh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.zzjgm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String zzjgm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.lxdh
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.czdh
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String czdh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.dzxx
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String dzxx;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.zydz
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String zydz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxbbm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String xxbbm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.sszgdwm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String sszgdwm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.szdcxlxm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String szdcxlxm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.szdjjsxm
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String szdjjsxm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.szdmzsx
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String szdmzsx;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxxz
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private BigDecimal xxxz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.xxrxnl
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private Short xxrxnl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.czxz
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private BigDecimal czxz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.czrxnl
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private Short czrxnl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.gzxz
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private BigDecimal gzxz;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.zjxyym
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String zjxyym;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.fjxyym
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String fjxyym;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.zsbj
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String zsbj;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.orgid
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private Long orgid;

    private long px;

    private String bjxx;

    private Organization org;

    private String xxsx;

    private String xxdwcc;

    private String bxlxname;

    private String xxbbname;

    private String xxdwccname;

    private String xxsxname;

    private BigDecimal dxxz;
    
    public BigDecimal getDxxz() {
        return dxxz;
    }

    public void setDxxz(BigDecimal dxxz) {
        this.dxxz = dxxz;
    }

    public String getBxlxname() {
        return bxlxname;
    }

    public void setBxlxname(String bxlxname) {
        this.bxlxname = bxlxname;
    }

    public String getXxbbname() {
        return xxbbname;
    }

    public void setXxbbname(String xxbbname) {
        this.xxbbname = xxbbname;
    }

    public String getXxdwccname() {
        return xxdwccname;
    }

    public void setXxdwccname(String xxdwccname) {
        this.xxdwccname = xxdwccname;
    }

    public String getXxsxname() {
        return xxsxname;
    }

    public void setXxsxname(String xxsxname) {
        this.xxsxname = xxsxname;
    }

    public String getXxdwcc() {
        return xxdwcc;
    }

    public void setXxdwcc(String xxdwcc) {
        this.xxdwcc = xxdwcc;
    }

    public String getXxsx() {
        return xxsx;
    }

    public void setXxsx(String xxsx) {
        this.xxsx = xxsx;
    }

    public Organization getOrg() {
        return org;
    }

    public void setOrg(Organization org) {
        this.org = org;
    }

    public long getPx() {
        return px;
    }

    public void setPx(long px) {
        this.px = px;
    }

    public String getBjxx() {
        return bjxx;
    }

    public void setBjxx(String bjxx) {
        this.bjxx = bjxx;
    }

    public Long getOrgid() {
        return orgid;
    }

    private List<SchoolPsychicteam> psychicyTeams;

    private List<SchoolPsychicjob> psychicyJobs;

    public List<SchoolPsychicteam> getPsychicyTeams() {
        return psychicyTeams;
    }

    public void setPsychicyTeams(List<SchoolPsychicteam> psychicyTeams) {
        this.psychicyTeams = psychicyTeams;
    }

    public List<SchoolPsychicjob> getPsychicyJobs() {
        return psychicyJobs;
    }

    public void setPsychicyJobs(List<SchoolPsychicjob> psychicyJobs) {
        this.psychicyJobs = psychicyJobs;
    }

    public void setOrgid(Long orgid) {
        this.orgid = orgid;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school.lsyg
     *
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    private String lsyg;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.id
     *
     * @return the value of school.id
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.id
     *
     * @param id
     *            the value for school.id
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxdm
     *
     * @return the value of school.xxdm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxdm() {
        return xxdm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxdm
     *
     * @param xxdm
     *            the value for school.xxdm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxdm(String xxdm) {
        this.xxdm = xxdm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxmc
     *
     * @return the value of school.xxmc
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxmc() {
        return xxmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxmc
     *
     * @param xxmc
     *            the value for school.xxmc
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxmc(String xxmc) {
        this.xxmc = xxmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxywmc
     *
     * @return the value of school.xxywmc
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxywmc() {
        return xxywmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxywmc
     *
     * @param xxywmc
     *            the value for school.xxywmc
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxywmc(String xxywmc) {
        this.xxywmc = xxywmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxdz
     *
     * @return the value of school.xxdz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxdz() {
        return xxdz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxdz
     *
     * @param xxdz
     *            the value for school.xxdz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxdz(String xxdz) {
        this.xxdz = xxdz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxyzbm
     *
     * @return the value of school.xxyzbm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxyzbm() {
        return xxyzbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxyzbm
     *
     * @param xxyzbm
     *            the value for school.xxyzbm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxyzbm(String xxyzbm) {
        this.xxyzbm = xxyzbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xzqhm
     *
     * @return the value of school.xzqhm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXzqhm() {
        return xzqhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xzqhm
     *
     * @param xzqhm
     *            the value for school.xzqhm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXzqhm(String xzqhm) {
        this.xzqhm = xzqhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.jxny
     *
     * @return the value of school.jxny
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getJxny() {
        return jxny;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.jxny
     *
     * @param jxny
     *            the value for school.jxny
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setJxny(String jxny) {
        this.jxny = jxny;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xqr
     *
     * @return the value of school.xqr
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXqr() {
        return xqr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xqr
     *
     * @param xqr
     *            the value for school.xqr
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXqr(String xqr) {
        this.xqr = xqr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxbxlxm
     *
     * @return the value of school.xxbxlxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxbxlxm() {
        return xxbxlxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxbxlxm
     *
     * @param xxbxlxm
     *            the value for school.xxbxlxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxbxlxm(String xxbxlxm) {
        this.xxbxlxm = xxbxlxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxjbzm
     *
     * @return the value of school.xxjbzm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxjbzm() {
        return xxjbzm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxjbzm
     *
     * @param xxjbzm
     *            the value for school.xxjbzm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxjbzm(String xxjbzm) {
        this.xxjbzm = xxjbzm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxzgbmm
     *
     * @return the value of school.xxzgbmm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxzgbmm() {
        return xxzgbmm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxzgbmm
     *
     * @param xxzgbmm
     *            the value for school.xxzgbmm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxzgbmm(String xxzgbmm) {
        this.xxzgbmm = xxzgbmm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.fddbrh
     *
     * @return the value of school.fddbrh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getFddbrh() {
        return fddbrh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.fddbrh
     *
     * @param fddbrh
     *            the value for school.fddbrh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setFddbrh(String fddbrh) {
        this.fddbrh = fddbrh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.frzsh
     *
     * @return the value of school.frzsh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getFrzsh() {
        return frzsh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.frzsh
     *
     * @param frzsh
     *            the value for school.frzsh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setFrzsh(String frzsh) {
        this.frzsh = frzsh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xzgh
     *
     * @return the value of school.xzgh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXzgh() {
        return xzgh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xzgh
     *
     * @param xzgh
     *            the value for school.xzgh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXzgh(String xzgh) {
        this.xzgh = xzgh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xzxm
     *
     * @return the value of school.xzxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXzxm() {
        return xzxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xzxm
     *
     * @param xzxm
     *            the value for school.xzxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXzxm(String xzxm) {
        this.xzxm = xzxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.dwfzrh
     *
     * @return the value of school.dwfzrh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getDwfzrh() {
        return dwfzrh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.dwfzrh
     *
     * @param dwfzrh
     *            the value for school.dwfzrh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setDwfzrh(String dwfzrh) {
        this.dwfzrh = dwfzrh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.zzjgm
     *
     * @return the value of school.zzjgm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getZzjgm() {
        return zzjgm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.zzjgm
     *
     * @param zzjgm
     *            the value for school.zzjgm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setZzjgm(String zzjgm) {
        this.zzjgm = zzjgm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.lxdh
     *
     * @return the value of school.lxdh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.lxdh
     *
     * @param lxdh
     *            the value for school.lxdh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.czdh
     *
     * @return the value of school.czdh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getCzdh() {
        return czdh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.czdh
     *
     * @param czdh
     *            the value for school.czdh
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setCzdh(String czdh) {
        this.czdh = czdh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.dzxx
     *
     * @return the value of school.dzxx
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getDzxx() {
        return dzxx;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.dzxx
     *
     * @param dzxx
     *            the value for school.dzxx
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setDzxx(String dzxx) {
        this.dzxx = dzxx;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.zydz
     *
     * @return the value of school.zydz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getZydz() {
        return zydz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.zydz
     *
     * @param zydz
     *            the value for school.zydz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setZydz(String zydz) {
        this.zydz = zydz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxbbm
     *
     * @return the value of school.xxbbm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getXxbbm() {
        return xxbbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxbbm
     *
     * @param xxbbm
     *            the value for school.xxbbm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxbbm(String xxbbm) {
        this.xxbbm = xxbbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.sszgdwm
     *
     * @return the value of school.sszgdwm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getSszgdwm() {
        return sszgdwm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.sszgdwm
     *
     * @param sszgdwm
     *            the value for school.sszgdwm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setSszgdwm(String sszgdwm) {
        this.sszgdwm = sszgdwm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.szdcxlxm
     *
     * @return the value of school.szdcxlxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getSzdcxlxm() {
        return szdcxlxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.szdcxlxm
     *
     * @param szdcxlxm
     *            the value for school.szdcxlxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setSzdcxlxm(String szdcxlxm) {
        this.szdcxlxm = szdcxlxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.szdjjsxm
     *
     * @return the value of school.szdjjsxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getSzdjjsxm() {
        return szdjjsxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.szdjjsxm
     *
     * @param szdjjsxm
     *            the value for school.szdjjsxm
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setSzdjjsxm(String szdjjsxm) {
        this.szdjjsxm = szdjjsxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.szdmzsx
     *
     * @return the value of school.szdmzsx
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getSzdmzsx() {
        return szdmzsx;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.szdmzsx
     *
     * @param szdmzsx
     *            the value for school.szdmzsx
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setSzdmzsx(String szdmzsx) {
        this.szdmzsx = szdmzsx;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxxz
     *
     * @return the value of school.xxxz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public BigDecimal getXxxz() {
        return xxxz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxxz
     *
     * @param xxxz
     *            the value for school.xxxz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxxz(BigDecimal xxxz) {
        this.xxxz = xxxz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.xxrxnl
     *
     * @return the value of school.xxrxnl
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public Short getXxrxnl() {
        return xxrxnl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.xxrxnl
     *
     * @param xxrxnl
     *            the value for school.xxrxnl
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setXxrxnl(Short xxrxnl) {
        this.xxrxnl = xxrxnl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.czxz
     *
     * @return the value of school.czxz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public BigDecimal getCzxz() {
        return czxz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.czxz
     *
     * @param czxz
     *            the value for school.czxz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setCzxz(BigDecimal czxz) {
        this.czxz = czxz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.czrxnl
     *
     * @return the value of school.czrxnl
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public Short getCzrxnl() {
        return czrxnl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.czrxnl
     *
     * @param czrxnl
     *            the value for school.czrxnl
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setCzrxnl(Short czrxnl) {
        this.czrxnl = czrxnl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.gzxz
     *
     * @return the value of school.gzxz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public BigDecimal getGzxz() {
        return gzxz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.gzxz
     *
     * @param gzxz
     *            the value for school.gzxz
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setGzxz(BigDecimal gzxz) {
        this.gzxz = gzxz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.zjxyym
     *
     * @return the value of school.zjxyym
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getZjxyym() {
        return zjxyym;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.zjxyym
     *
     * @param zjxyym
     *            the value for school.zjxyym
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setZjxyym(String zjxyym) {
        this.zjxyym = zjxyym;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.fjxyym
     *
     * @return the value of school.fjxyym
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getFjxyym() {
        return fjxyym;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.fjxyym
     *
     * @param fjxyym
     *            the value for school.fjxyym
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setFjxyym(String fjxyym) {
        this.fjxyym = fjxyym;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.zsbj
     *
     * @return the value of school.zsbj
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getZsbj() {
        return zsbj;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.zsbj
     *
     * @param zsbj
     *            the value for school.zsbj
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setZsbj(String zsbj) {
        this.zsbj = zsbj;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school.lsyg
     *
     * @return the value of school.lsyg
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public String getLsyg() {
        return lsyg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school.lsyg
     *
     * @param lsyg
     *            the value for school.lsyg
     * @mbggenerated Mon May 25 21:52:24 CST 2015
     */
    public void setLsyg(String lsyg) {
        this.lsyg = lsyg;
    }

    /**
     * 返回是否是小学 赵忠诚
     */
    public boolean isPrimaryschool() {
        if (xxbxlxm == null)
            return false;
        else if (xxbxlxm.startsWith(SchoolBXLX.primary_school.getId())) {
            return true;
        }
        return false;
    }

    public boolean isJuniorHighschool() {
        if (xxbxlxm.startsWith(SchoolBXLX.junior_school_31.getId())
                || xxbxlxm.startsWith(SchoolBXLX.junior_school_32.getId())
                || xxbxlxm.startsWith(SchoolBXLX.junior_school_33.getId())) {
            return true;
        }
        return false;
    }

    public boolean isSeniorHighschool() {
        if (xxbxlxm.startsWith(SchoolBXLX.senior_school_34.getId())
                || xxbxlxm.startsWith(SchoolBXLX.senior_school_35.getId())
                || xxbxlxm.startsWith(SchoolBXLX.senior_school_36.getId())
                || xxbxlxm.startsWith(SchoolBXLX.senior_school_37.getId())) {
            return true;
        }
        return false;
    }
    
    public boolean isDxschool() {
        if (xxbxlxm.startsWith(SchoolBXLX.junior_school_350.getId())) {
            return true;
        }
        return false;
    }

    /**
     * 返回学校组信息 用在gradecode表中
     */
    public int getSchoolGroup() {
        if (isPrimaryschool())
            return XueDuan.prim_school.getId();
        else if (isJuniorHighschool())
            return XueDuan.j_school.getId();
        else if (isSeniorHighschool())
            return XueDuan.s_school.getId();
        else
            return 0;
    }

    /**
     * 返回学段信息
     */
    public List<XueDuan> getXueDuan() {
        List<XueDuan> xueDuanList = new ArrayList<XueDuan>();
        if (isPrimaryschool()) {
            xueDuanList.add(XueDuan.prim_school);
        } else if (xxbxlxm.equals(SchoolBXLX.junior_school_312.getId())) {
            xueDuanList.add(XueDuan.prim_school);
            xueDuanList.add(XueDuan.j_school);
        } else if (xxbxlxm.equals(SchoolBXLX.senior_school_345.getId())) {
            xueDuanList.add(XueDuan.prim_school);
            xueDuanList.add(XueDuan.j_school);
            xueDuanList.add(XueDuan.s_school);
        } else if (xxbxlxm.equals(SchoolBXLX.senior_school_341.getId())) {
            xueDuanList.add(XueDuan.j_school);
            xueDuanList.add(XueDuan.s_school);
        } else if (isJuniorHighschool()) {
            xueDuanList.add(XueDuan.j_school);
        } else if (isSeniorHighschool()) {
            xueDuanList.add(XueDuan.s_school);
        }

        return xueDuanList;
    }

    /**
     * 获得学校的学制，如果是一贯制教育获得每个学段的学制之和
     */
    public BigDecimal getXZ() {
        if (isPrimaryschool())
            return xxxz;
        else if (xxbxlxm.equals(SchoolBXLX.junior_school_312.getId()))// 9年一贯教育
            return xxxz.add(czxz);
        else if (isJuniorHighschool())
            return czxz;
        else if (xxbxlxm.equals(SchoolBXLX.senior_school_341.getId()))// 完全中学
            return czxz.add(gzxz);
        else if (xxbxlxm.equals(SchoolBXLX.senior_school_345.getId()))// 12年一贯教育
            return xxxz.add(czxz).add(gzxz);
        else if (xxbxlxm.equals(SchoolBXLX.junior_school_350.getId()))// 大学
            return dxxz;
        else if (isSeniorHighschool())
            return gzxz;
        else
            return null;
    }

    /**
     * 获得每个学段的学制，根据学校类型自动判断，如果是9年一贯制教育
     */
    public HashMap<XueDuan, BigDecimal> getXZEveryXueDuan() {
        HashMap<XueDuan, BigDecimal> xd = new HashMap<XueDuan, BigDecimal>();
        if (isPrimaryschool())
            xd.put(XueDuan.prim_school, xxxz);
        else if (xxbxlxm.equals(SchoolBXLX.junior_school_312.getId())) {// 9年一贯教育
            xd.put(XueDuan.prim_school, xxxz);
            xd.put(XueDuan.j_school, czxz);
        } else if (isJuniorHighschool())
            xd.put(XueDuan.j_school, czxz);
        else if (xxbxlxm.equals(SchoolBXLX.senior_school_345.getId())) {// 12年一贯教育
            xd.put(XueDuan.prim_school, xxxz);
            xd.put(XueDuan.j_school, czxz);
            xd.put(XueDuan.s_school, gzxz);
        } else if (xxbxlxm.equals(SchoolBXLX.senior_school_341.getId())) {// 12年一贯教育)
            xd.put(XueDuan.j_school, czxz);
            xd.put(XueDuan.s_school, gzxz);

        } else if (isSeniorHighschool())
            xd.put(XueDuan.s_school, gzxz);

        return xd;
    }

    /**
     * 入学年龄
     */
    public Short getRxnl() {
        if (isPrimaryschool())
            return xxrxnl;
        else if (isJuniorHighschool())
            return czrxnl;
        else
            return null;
    }
}