package com.njpes.www.entity.baseinfo.organization;

public class SchoolPsychicteam {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school_psychicteam.id
     * 
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school_psychicteam.ryid
     * 
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    private Long ryid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school_psychicteam.gzzw
     * 
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    private String gzzw;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school_psychicteam.schoolid
     * 
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    private Long schoolid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column school_psychicteam.grjl
     * 
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    private String grjl;

    private String ryxm;// 人员姓名

    public String getRyxm() {
        return ryxm;
    }

    public void setRyxm(String ryxm) {
        this.ryxm = ryxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school_psychicteam.id
     * 
     * @return the value of school_psychicteam.id
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school_psychicteam.id
     * 
     * @param id
     *            the value for school_psychicteam.id
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school_psychicteam.ryid
     * 
     * @return the value of school_psychicteam.ryid
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public Long getRyid() {
        return ryid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school_psychicteam.ryid
     * 
     * @param ryid
     *            the value for school_psychicteam.ryid
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public void setRyid(Long ryid) {
        this.ryid = ryid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school_psychicteam.gzzw
     * 
     * @return the value of school_psychicteam.gzzw
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public String getGzzw() {
        return gzzw;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school_psychicteam.gzzw
     * 
     * @param gzzw
     *            the value for school_psychicteam.gzzw
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public void setGzzw(String gzzw) {
        this.gzzw = gzzw;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school_psychicteam.schoolid
     * 
     * @return the value of school_psychicteam.schoolid
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public Long getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school_psychicteam.schoolid
     * 
     * @param schoolid
     *            the value for school_psychicteam.schoolid
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public void setSchoolid(Long schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column school_psychicteam.grjl
     * 
     * @return the value of school_psychicteam.grjl
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public String getGrjl() {
        return grjl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column school_psychicteam.grjl
     * 
     * @param grjl
     *            the value for school_psychicteam.grjl
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    public void setGrjl(String grjl) {
        this.grjl = grjl;
    }
}