package com.njpes.www.dao.systeminfo;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.systeminfo.ExamdoStudent;
import com.njpes.www.entity.systeminfo.ExamdoStudentKey;
import com.njpes.www.utils.PageParameter;

public interface ExamdoStudentMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examdo_student
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    int deleteByPrimaryKey(ExamdoStudentKey key);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examdo_student
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    int insert(ExamdoStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examdo_student
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    int insertSelective(ExamdoStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examdo_student
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    ExamdoStudent selectByPrimaryKey(ExamdoStudentKey key);

    List<Map> queryExamdoStudentsByClassId(Map param);

    List<Map> queryExamdoStudentsByGradeId(Map param);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examdo_student
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    int updateByPrimaryKeySelective(ExamdoStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examdo_student
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ExamdoStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examdo_student
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    int updateByPrimaryKey(ExamdoStudent record);

    List<com.njpes.www.entity.systeminfo.ExamdoStudent> selectEntityByPage(
            @Param("examdoStudent") ExamdoStudent examdoStudent, @Param("page") PageParameter page,
            @Param("beginDate") Date beginDate, @Param("endDate") Date endDate);

    int resetExamdo(long id);

    int resetExamdoBatch(String[] ids);

    int resetExamdoMh(long id);

    int resetExamdoMhBatch(String[] ids);
}