package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobActivityRecordPsyresearchWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface JobActivityRecordPsyresearchMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psyresearch
     * 
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psyresearch
     * 
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    int insert(JobActivityRecordPsyresearchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psyresearch
     * 
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    int insertSelective(JobActivityRecordPsyresearchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psyresearch
     * 
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    JobActivityRecordPsyresearchWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psyresearch
     * 
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    int updateByPrimaryKeySelective(JobActivityRecordPsyresearchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psyresearch
     * 
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(JobActivityRecordPsyresearchWithBLOBs record);

    /**
     * @author 赵忠诚
     */

    List<JobActivityRecordPsyresearchWithBLOBs> findByPage(
            @Param("entity") JobActivityRecordPsyresearchWithBLOBs params, @Param("page") PageParameter page);

}