package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobActivityPlan;
import com.njpes.www.entity.workschedule.JobActivityPlanWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface JobActivityPlanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityplan
     * 
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityplan
     * 
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    int insert(JobActivityPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityplan
     * 
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    int insertSelective(JobActivityPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityplan
     * 
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    JobActivityPlanWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityplan
     * 
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    int updateByPrimaryKeySelective(JobActivityPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityplan
     * 
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(JobActivityPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityplan
     * 
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    int updateByPrimaryKey(JobActivityPlan record);

    /**
     * 查询学校录入的所有学�?
     * 
     * @param depid
     *            学校编码
     * @author 赵忠诚
     */
    List<String> getSchoolYearsBySchool(@Param("depid") long depid);

    /**
     * 分页查询活动计划
     * 
     * @author 赵忠诚
     */
    List<JobActivityPlanWithBLOBs> findByParamsPage(@Param("params") JobActivityPlanWithBLOBs param,
            @Param("page") PageParameter pageParams);

    /**
     * 更新状态位
     * 
     * @author 赵忠诚
     */
    int updateStateByPrimaryKey(@Param("record") JobActivityPlanWithBLOBs record);
}