package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobActivitySummary;
import com.njpes.www.entity.workschedule.JobActivitySummaryWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface JobActivitySummaryMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activity_summary
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activity_summary
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    int insert(JobActivitySummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activity_summary
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    int insertSelective(JobActivitySummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activity_summary
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    JobActivitySummaryWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activity_summary
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    int updateByPrimaryKeySelective(JobActivitySummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activity_summary
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(JobActivitySummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activity_summary
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    int updateByPrimaryKey(JobActivitySummary record);

    /**
     * @author 赵忠诚
     */

    List<JobActivitySummaryWithBLOBs> findByPage(@Param("entity") JobActivitySummaryWithBLOBs params,
            @Param("page") PageParameter page);

    List<String> getSchoolYearsBySchool(@Param("depid") Long depid);
}