package com.njpes.www.dao.workschedule;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobAttachment;

public interface JobAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_attachment
     * 
     * @mbggenerated Thu Jul 09 22:31:07 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_attachment
     * 
     * @mbggenerated Thu Jul 09 22:31:07 CST 2015
     */
    int insert(JobAttachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_attachment
     * 
     * @mbggenerated Thu Jul 09 22:31:07 CST 2015
     */
    int insertSelective(JobAttachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_attachment
     * 
     * @mbggenerated Thu Jul 09 22:31:07 CST 2015
     */
    JobAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_attachment
     * 
     * @mbggenerated Thu Jul 09 22:31:07 CST 2015
     */
    int updateByPrimaryKeySelective(JobAttachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_attachment
     * 
     * @mbggenerated Thu Jul 09 22:31:07 CST 2015
     */
    int updateByPrimaryKey(JobAttachment record);

    /**
     * 根据外键删除�?��的存储附件记�?
     * 
     * @author zzc
     */
    int deleteByUUid(@Param("uuid") String uuid);

    JobAttachment selectIdByUUid(@Param("uuid") String uuid);

}
