package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobActivityRecordPsycourseWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface JobActivityRecordPsycourseMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psycourse
     * 
     * @mbggenerated Mon Jul 13 21:48:25 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psycourse
     * 
     * @mbggenerated Mon Jul 13 21:48:25 CST 2015
     */
    int insert(JobActivityRecordPsycourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psycourse
     * 
     * @mbggenerated Mon Jul 13 21:48:25 CST 2015
     */
    int insertSelective(JobActivityRecordPsycourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psycourse
     * 
     * @mbggenerated Mon Jul 13 21:48:25 CST 2015
     */
    JobActivityRecordPsycourseWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psycourse
     * 
     * @mbggenerated Mon Jul 13 21:48:25 CST 2015
     */
    int updateByPrimaryKeySelective(JobActivityRecordPsycourseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_activityrecord_psycourse
     * 
     * @mbggenerated Mon Jul 13 21:48:25 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(JobActivityRecordPsycourseWithBLOBs record);

    /**
     * @author 赵忠诚
     */
    List<JobActivityRecordPsycourseWithBLOBs> findByPage(@Param("entity") JobActivityRecordPsycourseWithBLOBs params,
            @Param("page") PageParameter page);

}