package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobCongress;
import com.njpes.www.entity.workschedule.JobCongressWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface JobCongressMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_congress
     * 
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_congress
     * 
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    int insert(JobCongressWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_congress
     * 
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    int insertSelective(JobCongressWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_congress
     * 
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    JobCongressWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_congress
     * 
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    int updateByPrimaryKeySelective(JobCongressWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_congress
     * 
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(JobCongressWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_congress
     * 
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    int updateByPrimaryKey(JobCongress record);

    /**
     * @author 赵忠诚
     */
    public List<JobCongressWithBLOBs> findByPage(@Param("entity") JobCongressWithBLOBs entity,
            @Param("page") PageParameter page);
}