package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobNotice;
import com.njpes.www.entity.workschedule.JobNoticeWebQueryParam;
import com.njpes.www.entity.workschedule.JobNoticeWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface JobNoticeMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_notice
     * 
     * @mbggenerated Thu Jun 04 00:14:06 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_notice
     * 
     * @mbggenerated Thu Jun 04 00:14:06 CST 2015
     */
    int insert(JobNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_notice
     * 
     * @mbggenerated Thu Jun 04 00:14:06 CST 2015
     */
    int insertSelective(JobNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_notice
     * 
     * @mbggenerated Thu Jun 04 00:14:06 CST 2015
     */
    JobNoticeWithBLOBs selectByPrimaryKey(@Param("id") Long id, @Param("sendOrgid") long sendOrgid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_notice
     * 
     * @mbggenerated Thu Jun 04 00:14:06 CST 2015
     */
    int updateByPrimaryKeySelective(JobNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_notice
     * 
     * @mbggenerated Thu Jun 04 00:14:06 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(JobNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_notice
     * 
     * @mbggenerated Thu Jun 04 00:14:06 CST 2015
     */
    int updateByPrimaryKey(JobNotice record);

    /**
     * 根据查询条件查看信息
     * 
     * @author 赵忠诚
     */
    List<JobNoticeWithBLOBs> findByParamsPage(@Param("params") JobNoticeWebQueryParam params,
            @Param("page") PageParameter pageParams);

    List<JobNoticeWithBLOBs> findAllPage(@Param("params") JobNoticeWebQueryParam params,
            @Param("page") PageParameter pageParams);

    /**
     * 更新状态位
     * 
     * @author 赵忠诚
     */
    int updateStateByPrimaryKey(@Param("record") JobNoticeWithBLOBs record);

    JobNoticeWithBLOBs selectBaseInfo(@Param("id") Long id);

}