package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobPlanShare;

public interface JobPlanShareMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan_share
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan_share
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    int insert(JobPlanShare record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan_share
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    int insertSelective(JobPlanShare record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan_share
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    JobPlanShare selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan_share
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    int updateByPrimaryKeySelective(JobPlanShare record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan_share
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    int updateByPrimaryKey(JobPlanShare record);

    /**
     * 根据planid删除记录
     * 
     * @param planid
     * @return int
     * @author 赵忠诚
     */
    int deleteByPlanId(@Param("planid") long planid, @Param("sendOrgid") long sendOrgid);

    List<JobPlanShare> selectShareInfoBySendOrgid(@Param("planid") long planid, @Param("sendOrgid") long sendOrgid);
}