package com.njpes.www.dao.workschedule;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.workschedule.JobPlan;
import com.njpes.www.entity.workschedule.JobPlanWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface JobPlanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    int insert(JobPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    int insertSelective(JobPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    JobPlanWithBLOBs selectByPrimaryKey(@Param("id") Long id, @Param("sendOrgid") long sendOrgid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    int updateByPrimaryKeySelective(JobPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table job_plan
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(JobPlanWithBLOBs record);

    public List<JobPlan> findByParamsPage(@Param("params") JobPlanWithBLOBs param,
            @Param("page") PageParameter pageParams);

    JobPlanWithBLOBs selectBaseInfo(@Param("id") Long id);

    /**
     * 更新状态位
     * 
     * @author 赵忠诚
     */
    int updateStateByPrimaryKey(@Param("record") JobPlanWithBLOBs record);

}