package com.njpes.www.dao.scaletoollib;

import java.util.List;

import com.njpes.www.entity.scaletoollib.ExamresultDimStudent;
import com.njpes.www.entity.scaletoollib.ExamresultDimStudentWithBackGround;
import com.njpes.www.entity.scaletoollib.StatScope;

public interface ExamresultDimStudentMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Sat Mar 21 23:17:02 CST 2015
     */
    int deleteByPrimaryKey(Long resultId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Sat Mar 21 23:17:02 CST 2015
     */
    int insert(ExamresultDimStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Sat Mar 21 23:17:02 CST 2015
     */
    int insertSelective(ExamresultDimStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Sat Mar 21 23:17:02 CST 2015
     */
    ExamresultDimStudent selectByPrimaryKey(Long resultId);

    List<ExamresultDimStudentWithBackGround> getStudentResult(StatScope scope);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Sat Mar 21 23:17:02 CST 2015
     */
    int updateByPrimaryKeySelective(ExamresultDimStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Sat Mar 21 23:17:02 CST 2015
     */
    int updateByPrimaryKey(ExamresultDimStudent record);
}