package com.njpes.www.dao.scaletoollib;

import com.njpes.www.entity.scaletoollib.Scaledimexplain;

public interface ScaledimexplainMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scaledimexplain
     *
     * @mbggenerated Sat Mar 21 23:13:45 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scaledimexplain
     *
     * @mbggenerated Sat Mar 21 23:13:45 CST 2015
     */
    int insert(Scaledimexplain record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scaledimexplain
     *
     * @mbggenerated Sat Mar 21 23:13:45 CST 2015
     */
    int insertSelective(Scaledimexplain record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scaledimexplain
     *
     * @mbggenerated Sat Mar 21 23:13:45 CST 2015
     */
    Scaledimexplain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scaledimexplain
     *
     * @mbggenerated Sat Mar 21 23:13:45 CST 2015
     */
    int updateByPrimaryKeySelective(Scaledimexplain record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table scaledimexplain
     *
     * @mbggenerated Sat Mar 21 23:13:45 CST 2015
     */
    int updateByPrimaryKey(Scaledimexplain record);
}