package com.njpes.www.dao.scaletoollib;

import java.util.List;

import com.njpes.www.entity.scaletoollib.StatColumn;

public interface StatColumnMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table stat_columns
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table stat_columns
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    int insert(StatColumn record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table stat_columns
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    int insertSelective(StatColumn record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table stat_columns
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    StatColumn selectByPrimaryKey(Long id);

    /**
     * 根据表名获得所有可统计的属性名
     * 
     * @param tablename
     * @return
     */
    List<StatColumn> selectByTable(String tablename);

    /**
     * 根据表名和属性名获取字典表名
     * 
     * @param colname
     * @return
     */
    List<StatColumn> getDicTableName(StatColumn sc);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table stat_columns
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    int updateByPrimaryKeySelective(StatColumn record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table stat_columns
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    int updateByPrimaryKey(StatColumn record);
}