package com.njpes.www.dao.scaletoollib;

import java.util.Map;

import com.njpes.www.entity.scaletoollib.StudentDimExamResult;

public interface StudentDimExamResultMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Tue Apr 07 09:16:06 CST 2015
     */
    int deleteByPrimaryKey(Long resultId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Tue Apr 07 09:16:06 CST 2015
     */
    int insert(StudentDimExamResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Tue Apr 07 09:16:06 CST 2015
     */
    int insertSelective(StudentDimExamResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Tue Apr 07 09:16:06 CST 2015
     */
    StudentDimExamResult selectByPrimaryKey(Long resultId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Tue Apr 07 09:16:06 CST 2015
     */
    int updateByPrimaryKeySelective(StudentDimExamResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_student
     *
     * @mbggenerated Tue Apr 07 09:16:06 CST 2015
     */
    int updateByPrimaryKey(StudentDimExamResult record);

    int updateDimScore(Map paramets);
}