package com.njpes.www.dao.scaletoollib;

import java.util.Map;

import com.njpes.www.entity.scaletoollib.TeacherDimExamResult;

public interface TeacherDimExamResultMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_teacher
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    int deleteByPrimaryKey(Long resultId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_teacher
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    int insert(TeacherDimExamResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_teacher
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    int insertSelective(TeacherDimExamResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_teacher
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    TeacherDimExamResult selectByPrimaryKey(Long resultId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_teacher
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    int updateByPrimaryKeySelective(TeacherDimExamResult record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_dim_teacher
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    int updateByPrimaryKey(TeacherDimExamResult record);

    int updateDimScore(Map paramets);
}