package com.njpes.www.dao.assessmentcenter;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.assessmentcenter.ExamresultStudentMh;
import com.njpes.www.entity.assessmentcenter.ExamresultStudentMhWithBLOBs;

public interface ExamresultStudentMhMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_student_mh
     * 
     * @mbggenerated Tue Feb 02 11:46:05 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_student_mh
     * 
     * @mbggenerated Tue Feb 02 11:46:05 CST 2016
     */
    int insert(ExamresultStudentMhWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_student_mh
     * 
     * @mbggenerated Tue Feb 02 11:46:05 CST 2016
     */
    int insertSelective(ExamresultStudentMhWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_student_mh
     * 
     * @mbggenerated Tue Feb 02 11:46:05 CST 2016
     */
    ExamresultStudentMhWithBLOBs selectByPrimaryKey(@Param("id") Long id, @Param("typeflag") int typeflag);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_student_mh
     * 
     * @mbggenerated Tue Feb 02 11:46:05 CST 2016
     */
    int updateByPrimaryKeySelective(ExamresultStudentMhWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_student_mh
     * 
     * @mbggenerated Tue Feb 02 11:46:05 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ExamresultStudentMhWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table examresult_student_mh
     * 
     * @mbggenerated Tue Feb 02 11:46:05 CST 2016
     */
    int updateByPrimaryKey(ExamresultStudentMh record);
}