package com.njpes.www.dao.assessmentcenter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.assessmentcenter.InvesttaskEduSchool;

public interface InvesttaskEduSchoolMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask_edu_school
     *
     * @mbggenerated Thu Dec 31 13:04:51 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    int deleteByTaskid(long taskid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask_edu_school
     *
     * @mbggenerated Thu Dec 31 13:04:51 CST 2015
     */
    int insert(InvesttaskEduSchool record);

    int insertBatch(List records);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask_edu_school
     *
     * @mbggenerated Thu Dec 31 13:04:51 CST 2015
     */
    int insertSelective(InvesttaskEduSchool record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask_edu_school
     *
     * @mbggenerated Thu Dec 31 13:04:51 CST 2015
     */
    InvesttaskEduSchool selectByPrimaryKey(Long id);

    List getDistributableTask(@Param("orgid") long orgid, @Param("finished") boolean finished);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask_edu_school
     *
     * @mbggenerated Thu Dec 31 13:04:51 CST 2015
     */
    int updateByPrimaryKeySelective(InvesttaskEduSchool record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask_edu_school
     *
     * @mbggenerated Thu Dec 31 13:04:51 CST 2015
     */
    int updateByPrimaryKey(InvesttaskEduSchool record);

    int distributeTransferByEdu(InvesttaskEduSchool record);

    int distributeTransferBySchool(InvesttaskEduSchool record);
}