package com.njpes.www.dao.assessmentcenter;

import com.njpes.www.entity.assessmentcenter.InvestTaskUser;

public interface InvestTaskUserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_task_user
     *
     * @mbggenerated Sun Jan 10 10:43:11 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_task_user
     *
     * @mbggenerated Sun Jan 10 10:43:11 CST 2016
     */
    int insert(InvestTaskUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_task_user
     *
     * @mbggenerated Sun Jan 10 10:43:11 CST 2016
     */
    int insertSelective(InvestTaskUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_task_user
     *
     * @mbggenerated Sun Jan 10 10:43:11 CST 2016
     */
    InvestTaskUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_task_user
     *
     * @mbggenerated Sun Jan 10 10:43:11 CST 2016
     */
    int updateByPrimaryKeySelective(InvestTaskUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_task_user
     *
     * @mbggenerated Sun Jan 10 10:43:11 CST 2016
     */
    int updateByPrimaryKey(InvestTaskUser record);
}