package com.njpes.www.dao.assessmentcenter;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.assessmentcenter.Investtask;
import com.njpes.www.entity.assessmentcenter.InvesttaskWithBLOBs;
import com.njpes.www.entity.scaletoollib.InvestDispatcherFilterParam;
import com.njpes.www.utils.PageParameter;

public interface InvesttaskMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    int insert(InvesttaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    int insertSelective(InvesttaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    InvesttaskWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    int updateByPrimaryKeySelective(InvesttaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(InvesttaskWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investtask
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    int updateByPrimaryKey(Investtask record);

    List<InvesttaskWithBLOBs> selectAllInvestTaskForEduByPage(
            @Param("investDispatcherFilterParam") InvestDispatcherFilterParam it, @Param("page") PageParameter page);

    List<InvesttaskWithBLOBs> selectAllInvestTaskForSchoolByPage(
            @Param("investDispatcherFilterParam") InvestDispatcherFilterParam it, @Param("page") PageParameter page);

    public Date checkProcessingStatus(@Param("taskid") long taskid, @Param("ownerid") long ownerid);
}