package com.njpes.www.dao.assessmentcenter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.assessmentcenter.InvestExam;
import com.njpes.www.utils.PageParameter;

public interface InvestExamMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_exam
     *
     * @mbggenerated Sat Jun 06 22:01:06 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * shibin add for delete invest in batch
     */
    int deleteByPrimaryKeys(List ids);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_exam
     *
     * @mbggenerated Sat Jun 06 22:01:06 CST 2015
     */
    int insert(InvestExam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_exam
     *
     * @mbggenerated Sat Jun 06 22:01:06 CST 2015
     */
    int insertSelective(InvestExam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_exam
     *
     * @mbggenerated Sat Jun 06 22:01:06 CST 2015
     */
    InvestExam selectByPrimaryKey(Integer id);

    /**
     * 查询所有的调查问卷
     * 
     * @return
     */
    List<InvestExam> selectAllInvestByPage(@Param("invest") InvestExam ie, @Param("page") PageParameter page);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_exam
     *
     * @mbggenerated Sat Jun 06 22:01:06 CST 2015
     */
    int updateByPrimaryKeySelective(InvestExam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_exam
     *
     * @mbggenerated Sat Jun 06 22:01:06 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(InvestExam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table invest_exam
     *
     * @mbggenerated Sat Jun 06 22:01:06 CST 2015
     */
    int updateByPrimaryKey(InvestExam record);
}