package com.njpes.www.dao.assessmentcenter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.assessmentcenter.InvestdoSchool;
import com.njpes.www.entity.assessmentcenter.MyInvesttask;
import com.njpes.www.entity.scaletoollib.InvestDispatcherFilterParam;
import com.njpes.www.utils.PageParameter;

public interface InvestdoSchoolMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investdo_school
     *
     * @mbggenerated Sun Dec 27 21:07:13 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    int deleteByTaskid(Long itid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investdo_school
     *
     * @mbggenerated Sun Dec 27 21:07:13 CST 2015
     */
    int insert(InvestdoSchool record);

    int insertBatch(List<InvestdoSchool> records);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investdo_school
     *
     * @mbggenerated Sun Dec 27 21:07:13 CST 2015
     */
    int insertSelective(InvestdoSchool record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investdo_school
     *
     * @mbggenerated Sun Dec 27 21:07:13 CST 2015
     */
    InvestdoSchool selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investdo_school
     *
     * @mbggenerated Sun Dec 27 21:07:13 CST 2015
     */
    int updateByPrimaryKeySelective(InvestdoSchool record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table investdo_school
     *
     * @mbggenerated Sun Dec 27 21:07:13 CST 2015
     */
    int updateByPrimaryKey(InvestdoSchool record);

    List getInvestdoByPage(@Param("investDispatcherFilterParam") InvestDispatcherFilterParam it,
            @Param("page") PageParameter page);

    MyInvesttask getInvestdoById(String id);
}