package com.njpes.www.entity.consultcenter;

import java.util.Date;

public class Record {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.id
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.username
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.data
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Date data;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.teacherid
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Long teacherid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.consultationModeId
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Long consultationmodeid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.consultationTypeId
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Long consultationtypeid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.sfzjh
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private String sfzjh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.xh
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private String xh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.objtype
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private String objtype;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.schoolid
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Long schoolid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.bjid
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Long bjid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.njid
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Byte njid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.xbm
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private Boolean xbm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_record.describes
     * 
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    private String describes;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.id
     * 
     * @return the value of coach_record.id
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.id
     * 
     * @param id
     *            the value for coach_record.id
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.username
     * 
     * @return the value of coach_record.username
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.username
     * 
     * @param username
     *            the value for coach_record.username
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.data
     * 
     * @return the value of coach_record.data
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Date getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.data
     * 
     * @param data
     *            the value for coach_record.data
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setData(Date data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.teacherid
     * 
     * @return the value of coach_record.teacherid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.teacherid
     * 
     * @param teacherid
     *            the value for coach_record.teacherid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.consultationModeId
     * 
     * @return the value of coach_record.consultationModeId
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Long getConsultationmodeid() {
        return consultationmodeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.consultationModeId
     * 
     * @param consultationmodeid
     *            the value for coach_record.consultationModeId
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setConsultationmodeid(Long consultationmodeid) {
        this.consultationmodeid = consultationmodeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.consultationTypeId
     * 
     * @return the value of coach_record.consultationTypeId
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Long getConsultationtypeid() {
        return consultationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.consultationTypeId
     * 
     * @param consultationtypeid
     *            the value for coach_record.consultationTypeId
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setConsultationtypeid(Long consultationtypeid) {
        this.consultationtypeid = consultationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.sfzjh
     * 
     * @return the value of coach_record.sfzjh
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public String getSfzjh() {
        return sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.sfzjh
     * 
     * @param sfzjh
     *            the value for coach_record.sfzjh
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setSfzjh(String sfzjh) {
        this.sfzjh = sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.xh
     * 
     * @return the value of coach_record.xh
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.xh
     * 
     * @param xh
     *            the value for coach_record.xh
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setXh(String xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.objtype
     * 
     * @return the value of coach_record.objtype
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public String getObjtype() {
        return objtype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.objtype
     * 
     * @param objtype
     *            the value for coach_record.objtype
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setObjtype(String objtype) {
        this.objtype = objtype;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.schoolid
     * 
     * @return the value of coach_record.schoolid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Long getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.schoolid
     * 
     * @param schoolid
     *            the value for coach_record.schoolid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setSchoolid(Long schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.bjid
     * 
     * @return the value of coach_record.bjid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Long getBjid() {
        return bjid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.bjid
     * 
     * @param bjid
     *            the value for coach_record.bjid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setBjid(Long bjid) {
        this.bjid = bjid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.njid
     * 
     * @return the value of coach_record.njid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Byte getNjid() {
        return njid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.njid
     * 
     * @param njid
     *            the value for coach_record.njid
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setNjid(Byte njid) {
        this.njid = njid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.xbm
     * 
     * @return the value of coach_record.xbm
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public Boolean getXbm() {
        return xbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.xbm
     * 
     * @param xbm
     *            the value for coach_record.xbm
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setXbm(Boolean xbm) {
        this.xbm = xbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_record.describes
     * 
     * @return the value of coach_record.describes
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_record.describes
     * 
     * @param describes
     *            the value for coach_record.describes
     * @mbggenerated Sat Mar 05 11:36:39 CST 2016
     */
    public void setDescribes(String describes) {
        this.describes = describes;
    }
}