package com.njpes.www.entity.consultcenter;

import java.util.Date;

public class Scheduling {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_scheduling.id
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_scheduling.schoolid
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    private Long schoolid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_scheduling.timeid
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    private Integer timeid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_scheduling.teacherid
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    private Long teacherid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_scheduling.date
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_scheduling.id
     * 
     * @return the value of coach_scheduling.id
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_scheduling.id
     * 
     * @param id
     *            the value for coach_scheduling.id
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_scheduling.schoolid
     * 
     * @return the value of coach_scheduling.schoolid
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public Long getSchoolid() {
        return schoolid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_scheduling.schoolid
     * 
     * @param schoolid
     *            the value for coach_scheduling.schoolid
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public void setSchoolid(Long schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_scheduling.timeid
     * 
     * @return the value of coach_scheduling.timeid
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public Integer getTimeid() {
        return timeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_scheduling.timeid
     * 
     * @param timeid
     *            the value for coach_scheduling.timeid
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public void setTimeid(Integer timeid) {
        this.timeid = timeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_scheduling.teacherid
     * 
     * @return the value of coach_scheduling.teacherid
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_scheduling.teacherid
     * 
     * @param teacherid
     *            the value for coach_scheduling.teacherid
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_scheduling.date
     * 
     * @return the value of coach_scheduling.date
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_scheduling.date
     * 
     * @param date
     *            the value for coach_scheduling.date
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }
}