package com.njpes.www.entity.consultcenter;

public class TeamPerson {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_team_person.id
     *
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_team_person.teamid
     *
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    private Long teamid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_team_person.memberid
     *
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    private Long memberid;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_team_person.id
     *
     * @return the value of coach_team_person.id
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_team_person.id
     *
     * @param id
     *            the value for coach_team_person.id
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_team_person.teamid
     *
     * @return the value of coach_team_person.teamid
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    public Long getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_team_person.teamid
     *
     * @param teamid
     *            the value for coach_team_person.teamid
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    public void setTeamid(Long teamid) {
        this.teamid = teamid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_team_person.memberid
     *
     * @return the value of coach_team_person.memberid
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    public Long getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_team_person.memberid
     *
     * @param memberid
     *            the value for coach_team_person.memberid
     * @mbggenerated Sun May 24 17:09:51 CST 2015
     */
    public void setMemberid(Long memberid) {
        this.memberid = memberid;
    }
}