package com.njpes.www.entity.consultcenter;

public class WarningInterveneTWithBLOBs extends WarningInterveneT {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_teacher.process
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    private String process;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_teacher.record
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    private String record;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_teacher.process
     * 
     * @return the value of coach_warning_teacher.process
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_teacher.process
     * 
     * @param process
     *            the value for coach_warning_teacher.process
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    public void setProcess(String process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_teacher.record
     * 
     * @return the value of coach_warning_teacher.record
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_teacher.record
     * 
     * @param record
     *            the value for coach_warning_teacher.record
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    public void setRecord(String record) {
        this.record = record;
    }
}