package com.njpes.www.entity.consultcenter;

import java.util.Date;

public class WarningInterveneS {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.id
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.studentid
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private Long studentid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.name
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.sex
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.cardid
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String cardid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.class_name
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String className;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.grade
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String grade;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.type
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String type;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.result
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String result;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.status
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String status;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.level
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String level;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.warning_time
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private Date warningTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.intervene_time
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private Date interveneTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.examresult_id
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private Long examresultId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.school_id
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private Long schoolId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.groupid
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private Integer groupid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.dispose_type
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String disposeType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column coach_warning_student.dispose_person
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    private String disposePerson;

    private String disposeRoleId;
    
    private String schoolname;

    public String getSchoolname() {
        return schoolname;
    }

    public void setSchoolname(String schoolname) {
        this.schoolname = schoolname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.id
     * 
     * @return the value of coach_warning_student.id
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.id
     * 
     * @param id
     *            the value for coach_warning_student.id
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.studentid
     * 
     * @return the value of coach_warning_student.studentid
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public Long getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.studentid
     * 
     * @param studentid
     *            the value for coach_warning_student.studentid
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setStudentid(Long studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.name
     * 
     * @return the value of coach_warning_student.name
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.name
     * 
     * @param name
     *            the value for coach_warning_student.name
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.sex
     * 
     * @return the value of coach_warning_student.sex
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.sex
     * 
     * @param sex
     *            the value for coach_warning_student.sex
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.cardid
     * 
     * @return the value of coach_warning_student.cardid
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.cardid
     * 
     * @param cardid
     *            the value for coach_warning_student.cardid
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setCardid(String cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.class_name
     * 
     * @return the value of coach_warning_student.class_name
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.class_name
     * 
     * @param className
     *            the value for coach_warning_student.class_name
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.grade
     * 
     * @return the value of coach_warning_student.grade
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.grade
     * 
     * @param grade
     *            the value for coach_warning_student.grade
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.type
     * 
     * @return the value of coach_warning_student.type
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.type
     * 
     * @param type
     *            the value for coach_warning_student.type
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.result
     * 
     * @return the value of coach_warning_student.result
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.result
     * 
     * @param result
     *            the value for coach_warning_student.result
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.status
     * 
     * @return the value of coach_warning_student.status
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.status
     * 
     * @param status
     *            the value for coach_warning_student.status
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.level
     * 
     * @return the value of coach_warning_student.level
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.level
     * 
     * @param level
     *            the value for coach_warning_student.level
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.warning_time
     * 
     * @return the value of coach_warning_student.warning_time
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public Date getWarningTime() {
        return warningTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.warning_time
     * 
     * @param warningTime
     *            the value for coach_warning_student.warning_time
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setWarningTime(Date warningTime) {
        this.warningTime = warningTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.intervene_time
     * 
     * @return the value of coach_warning_student.intervene_time
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public Date getInterveneTime() {
        return interveneTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.intervene_time
     * 
     * @param interveneTime
     *            the value for coach_warning_student.intervene_time
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setInterveneTime(Date interveneTime) {
        this.interveneTime = interveneTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.examresult_id
     * 
     * @return the value of coach_warning_student.examresult_id
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public Long getExamresultId() {
        return examresultId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.examresult_id
     * 
     * @param examresultId
     *            the value for coach_warning_student.examresult_id
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setExamresultId(Long examresultId) {
        this.examresultId = examresultId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.school_id
     * 
     * @return the value of coach_warning_student.school_id
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.school_id
     * 
     * @param schoolId
     *            the value for coach_warning_student.school_id
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.groupid
     * 
     * @return the value of coach_warning_student.groupid
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.groupid
     * 
     * @param groupid
     *            the value for coach_warning_student.groupid
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.dispose_type
     * 
     * @return the value of coach_warning_student.dispose_type
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getDisposeType() {
        return disposeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.dispose_type
     * 
     * @param disposeType
     *            the value for coach_warning_student.dispose_type
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setDisposeType(String disposeType) {
        this.disposeType = disposeType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column coach_warning_student.dispose_person
     * 
     * @return the value of coach_warning_student.dispose_person
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public String getDisposePerson() {
        return disposePerson;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column coach_warning_student.dispose_person
     * 
     * @param disposePerson
     *            the value for coach_warning_student.dispose_person
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    public void setDisposePerson(String disposePerson) {
        this.disposePerson = disposePerson;
    }

    public String getDisposeRoleId() {
        return disposeRoleId;
    }

    public void setDisposeRoleId(String disposeRoleId) {
        this.disposeRoleId = disposeRoleId;
    }

}