package com.njpes.www.entity.consultcenter;

import java.util.Date;

public class WarningStudent {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.id
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.xm
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String xm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.xbm
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String xbm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.sfzjh
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String sfzjh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.nj
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String nj;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.bh
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String bh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.bjmch
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String bjmch;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.njmc
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String njmc;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.title
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.scale_id
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Integer scaleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.ok_time
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Date okTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.questionnum
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Integer questionnum;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.iswarnsure
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Byte iswarnsure;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.warning_grade
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Integer warningGrade;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.orgid
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Integer orgid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column view_warning_student.groupid
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    private Integer groupid;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.id
     * 
     * @return the value of view_warning_student.id
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.id
     * 
     * @param id
     *            the value for view_warning_student.id
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.xm
     * 
     * @return the value of view_warning_student.xm
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.xm
     * 
     * @param xm
     *            the value for view_warning_student.xm
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setXm(String xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.xbm
     * 
     * @return the value of view_warning_student.xbm
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getXbm() {
        return xbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.xbm
     * 
     * @param xbm
     *            the value for view_warning_student.xbm
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setXbm(String xbm) {
        this.xbm = xbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.sfzjh
     * 
     * @return the value of view_warning_student.sfzjh
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getSfzjh() {
        return sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.sfzjh
     * 
     * @param sfzjh
     *            the value for view_warning_student.sfzjh
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setSfzjh(String sfzjh) {
        this.sfzjh = sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.nj
     * 
     * @return the value of view_warning_student.nj
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getNj() {
        return nj;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.nj
     * 
     * @param nj
     *            the value for view_warning_student.nj
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setNj(String nj) {
        this.nj = nj;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.bh
     * 
     * @return the value of view_warning_student.bh
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.bh
     * 
     * @param bh
     *            the value for view_warning_student.bh
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setBh(String bh) {
        this.bh = bh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.bjmch
     * 
     * @return the value of view_warning_student.bjmch
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getBjmch() {
        return bjmch;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.bjmch
     * 
     * @param bjmch
     *            the value for view_warning_student.bjmch
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setBjmch(String bjmch) {
        this.bjmch = bjmch;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.njmc
     * 
     * @return the value of view_warning_student.njmc
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getNjmc() {
        return njmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.njmc
     * 
     * @param njmc
     *            the value for view_warning_student.njmc
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setNjmc(String njmc) {
        this.njmc = njmc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.title
     * 
     * @return the value of view_warning_student.title
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.title
     * 
     * @param title
     *            the value for view_warning_student.title
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.scale_id
     * 
     * @return the value of view_warning_student.scale_id
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Integer getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.scale_id
     * 
     * @param scaleId
     *            the value for view_warning_student.scale_id
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setScaleId(Integer scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.ok_time
     * 
     * @return the value of view_warning_student.ok_time
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Date getOkTime() {
        return okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.ok_time
     * 
     * @param okTime
     *            the value for view_warning_student.ok_time
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setOkTime(Date okTime) {
        this.okTime = okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.questionnum
     * 
     * @return the value of view_warning_student.questionnum
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Integer getQuestionnum() {
        return questionnum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.questionnum
     * 
     * @param questionnum
     *            the value for view_warning_student.questionnum
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setQuestionnum(Integer questionnum) {
        this.questionnum = questionnum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.iswarnsure
     * 
     * @return the value of view_warning_student.iswarnsure
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Byte getIswarnsure() {
        return iswarnsure;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.iswarnsure
     * 
     * @param iswarnsure
     *            the value for view_warning_student.iswarnsure
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setIswarnsure(Byte iswarnsure) {
        this.iswarnsure = iswarnsure;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.warning_grade
     * 
     * @return the value of view_warning_student.warning_grade
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Integer getWarningGrade() {
        return warningGrade;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.warning_grade
     * 
     * @param warningGrade
     *            the value for view_warning_student.warning_grade
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setWarningGrade(Integer warningGrade) {
        this.warningGrade = warningGrade;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.orgid
     * 
     * @return the value of view_warning_student.orgid
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.orgid
     * 
     * @param orgid
     *            the value for view_warning_student.orgid
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column view_warning_student.groupid
     * 
     * @return the value of view_warning_student.groupid
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column view_warning_student.groupid
     * 
     * @param groupid
     *            the value for view_warning_student.groupid
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }
}