package com.njpes.www.entity.systeminfo;

public class ExamdoStudentKey {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_student.id
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_student.bj
     *
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    private Long bj;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_student.id
     *
     * @return the value of examdo_student.id
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_student.id
     *
     * @param id
     *            the value for examdo_student.id
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_student.bj
     *
     * @return the value of examdo_student.bj
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    public Long getBj() {
        return bj;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_student.bj
     *
     * @param bj
     *            the value for examdo_student.bj
     * @mbggenerated Sat Nov 21 17:06:55 CST 2015
     */
    public void setBj(Long bj) {
        this.bj = bj;
    }
}