package com.njpes.www.entity.systeminfo;

import java.util.Date;

public class ExamdoTeacher {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.id
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.user_id
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Long userId;

    private String xm;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.scale_id
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Integer scaleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.lo_time
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Date loTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.hi_time
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Date hiTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.ok_time
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Date okTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.flag
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Byte flag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.taskid
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Long taskid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.roleid
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Integer roleid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.cityid
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.countyid
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private String countyid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_teacher.orgid
     *
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    private Long orgid;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.id
     *
     * @return the value of examdo_teacher.id
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.id
     *
     * @param id
     *            the value for examdo_teacher.id
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.user_id
     *
     * @return the value of examdo_teacher.user_id
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.user_id
     *
     * @param userId
     *            the value for examdo_teacher.user_id
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getXm() {
        return xm;
    }

    public void setXm(String xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.scale_id
     *
     * @return the value of examdo_teacher.scale_id
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Integer getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.scale_id
     *
     * @param scaleId
     *            the value for examdo_teacher.scale_id
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setScaleId(Integer scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.lo_time
     *
     * @return the value of examdo_teacher.lo_time
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Date getLoTime() {
        return loTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.lo_time
     *
     * @param loTime
     *            the value for examdo_teacher.lo_time
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setLoTime(Date loTime) {
        this.loTime = loTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.hi_time
     *
     * @return the value of examdo_teacher.hi_time
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Date getHiTime() {
        return hiTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.hi_time
     *
     * @param hiTime
     *            the value for examdo_teacher.hi_time
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setHiTime(Date hiTime) {
        this.hiTime = hiTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.ok_time
     *
     * @return the value of examdo_teacher.ok_time
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Date getOkTime() {
        return okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.ok_time
     *
     * @param okTime
     *            the value for examdo_teacher.ok_time
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setOkTime(Date okTime) {
        this.okTime = okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.flag
     *
     * @return the value of examdo_teacher.flag
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.flag
     *
     * @param flag
     *            the value for examdo_teacher.flag
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.taskid
     *
     * @return the value of examdo_teacher.taskid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Long getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.taskid
     *
     * @param taskid
     *            the value for examdo_teacher.taskid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.roleid
     *
     * @return the value of examdo_teacher.roleid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.roleid
     *
     * @param roleid
     *            the value for examdo_teacher.roleid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.cityid
     *
     * @return the value of examdo_teacher.cityid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.cityid
     *
     * @param cityid
     *            the value for examdo_teacher.cityid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.countyid
     *
     * @return the value of examdo_teacher.countyid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public String getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.countyid
     *
     * @param countyid
     *            the value for examdo_teacher.countyid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setCountyid(String countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_teacher.orgid
     *
     * @return the value of examdo_teacher.orgid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public Long getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_teacher.orgid
     *
     * @param orgid
     *            the value for examdo_teacher.orgid
     * @mbggenerated Sat Nov 21 17:07:15 CST 2015
     */
    public void setOrgid(Long orgid) {
        this.orgid = orgid;
    }
}