package com.njpes.www.entity.workschedule;

public class JobActivityRecordPsyresearchWithBLOBs extends JobActivityRecordPsyresearch {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyresearch.subject
     *
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    private String subject;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyresearch.content
     *
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyresearch.publishbooks
     *
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    private String publishbooks;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyresearch.rewards
     *
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    private String rewards;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyresearch.specialrecord
     *
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    //多文本编辑器未用字段，目前多文本编辑器使用content字段
    private String specialrecord;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyresearch.subject
     *
     * @return the value of job_activityrecord_psyresearch.subject
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyresearch.subject
     *
     * @param subject
     *            the value for job_activityrecord_psyresearch.subject
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyresearch.content
     *
     * @return the value of job_activityrecord_psyresearch.content
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyresearch.content
     *
     * @param content
     *            the value for job_activityrecord_psyresearch.content
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyresearch.publishbooks
     *
     * @return the value of job_activityrecord_psyresearch.publishbooks
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public String getPublishbooks() {
        return publishbooks;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyresearch.publishbooks
     *
     * @param publishbooks
     *            the value for job_activityrecord_psyresearch.publishbooks
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public void setPublishbooks(String publishbooks) {
        this.publishbooks = publishbooks;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyresearch.rewards
     *
     * @return the value of job_activityrecord_psyresearch.rewards
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public String getRewards() {
        return rewards;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyresearch.rewards
     *
     * @param rewards
     *            the value for job_activityrecord_psyresearch.rewards
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public void setRewards(String rewards) {
        this.rewards = rewards;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyresearch.specialrecord
     *
     * @return the value of job_activityrecord_psyresearch.specialrecord
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public String getSpecialrecord() {
        return specialrecord;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyresearch.specialrecord
     *
     * @param specialrecord
     *            the value for job_activityrecord_psyresearch.specialrecord
     * @mbggenerated Sat Jul 18 23:19:07 CST 2015
     */
    public void setSpecialrecord(String specialrecord) {
        this.specialrecord = specialrecord;
    }

}