package com.njpes.www.entity.workschedule;

public class JobActivityRecordPsyactWithBLOBs extends JobActivityRecordPsyact {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyact.title
     *
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyact.content
     *
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyact.target
     *
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    //多文本编辑器未用字段，目前多文本编辑器使用content字段
    private String target;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyact.process
     *
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    private String process;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityrecord_psyact.specialrecord
     *
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    //多文本编辑器未用字段，目前多文本编辑器使用content字段
    private String specialrecord;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyact.title
     *
     * @return the value of job_activityrecord_psyact.title
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyact.title
     *
     * @param title
     *            the value for job_activityrecord_psyact.title
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyact.content
     *
     * @return the value of job_activityrecord_psyact.content
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyact.content
     *
     * @param content
     *            the value for job_activityrecord_psyact.content
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyact.target
     *
     * @return the value of job_activityrecord_psyact.target
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyact.target
     *
     * @param target
     *            the value for job_activityrecord_psyact.target
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyact.process
     *
     * @return the value of job_activityrecord_psyact.process
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyact.process
     *
     * @param process
     *            the value for job_activityrecord_psyact.process
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public void setProcess(String process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityrecord_psyact.specialrecord
     *
     * @return the value of job_activityrecord_psyact.specialrecord
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public String getSpecialrecord() {
        return specialrecord;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityrecord_psyact.specialrecord
     *
     * @param specialrecord
     *            the value for job_activityrecord_psyact.specialrecord
     * @mbggenerated Tue Jul 21 00:22:22 CST 2015
     */
    public void setSpecialrecord(String specialrecord) {
        this.specialrecord = specialrecord;
    }

}