package com.njpes.www.entity.workschedule;

import java.util.Date;

public class JobActivitySummary {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.id
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.title
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.schoolyear
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private String schoolyear;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.term
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private String term;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.activitycatalog
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private String activitycatalog;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.activitytype
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private String activitytype;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.create_time
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.author
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private String author;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.dep
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private Long dep;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activity_summary.modify_time
     * 
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    private Date modifyTime;

    private Date querystarttime;

    private Date queryendtime;

    public Date getQuerystarttime() {
        return querystarttime;
    }

    public void setQuerystarttime(Date querystarttime) {
        this.querystarttime = querystarttime;
    }

    public Date getQueryendtime() {
        return queryendtime;
    }

    public void setQueryendtime(Date queryendtime) {
        this.queryendtime = queryendtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.id
     * 
     * @return the value of job_activity_summary.id
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.id
     * 
     * @param id
     *            the value for job_activity_summary.id
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.title
     * 
     * @return the value of job_activity_summary.title
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.title
     * 
     * @param title
     *            the value for job_activity_summary.title
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.schoolyear
     * 
     * @return the value of job_activity_summary.schoolyear
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public String getSchoolyear() {
        return schoolyear;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.schoolyear
     * 
     * @param schoolyear
     *            the value for job_activity_summary.schoolyear
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setSchoolyear(String schoolyear) {
        this.schoolyear = schoolyear;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.term
     * 
     * @return the value of job_activity_summary.term
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.term
     * 
     * @param term
     *            the value for job_activity_summary.term
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setTerm(String term) {
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.activitycatalog
     * 
     * @return the value of job_activity_summary.activitycatalog
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public String getActivitycatalog() {
        return activitycatalog;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.activitycatalog
     * 
     * @param activitycatalog
     *            the value for job_activity_summary.activitycatalog
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setActivitycatalog(String activitycatalog) {
        this.activitycatalog = activitycatalog;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.activitytype
     * 
     * @return the value of job_activity_summary.activitytype
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public String getActivitytype() {
        return activitytype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.activitytype
     * 
     * @param activitytype
     *            the value for job_activity_summary.activitytype
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setActivitytype(String activitytype) {
        this.activitytype = activitytype;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.create_time
     * 
     * @return the value of job_activity_summary.create_time
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.create_time
     * 
     * @param createTime
     *            the value for job_activity_summary.create_time
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.author
     * 
     * @return the value of job_activity_summary.author
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.author
     * 
     * @param author
     *            the value for job_activity_summary.author
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.dep
     * 
     * @return the value of job_activity_summary.dep
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public Long getDep() {
        return dep;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.dep
     * 
     * @param dep
     *            the value for job_activity_summary.dep
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setDep(Long dep) {
        this.dep = dep;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activity_summary.modify_time
     * 
     * @return the value of job_activity_summary.modify_time
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activity_summary.modify_time
     * 
     * @param modifyTime
     *            the value for job_activity_summary.modify_time
     * @mbggenerated Sun Jul 19 22:30:49 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}