package com.njpes.www.entity.workschedule;

public class JobActivityPlanWithBLOBs extends JobActivityPlan {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.title
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.target
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    //多文本编辑器字段，暂未用，目前使用的编辑器字段content
    private String target;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.ideology
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    //多文本编辑器字段，暂未用，目前使用的编辑器字段content
    private String ideology;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.content
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.auditext
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    private String auditext;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.jobmainpoint
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    //多文本编辑器字段，暂未用，目前使用的编辑器字段content
    private String jobmainpoint;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.arrange
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    //多文本编辑器字段，暂未用，目前使用的编辑器字段content
    private String arrange;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_activityplan.guarantee
     *
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    //多文本编辑器字段，暂未用，目前使用的编辑器字段content
    private String guarantee;

    private boolean canAudit;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.title
     *
     * @return the value of job_activityplan.title
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */

    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.title
     *
     * @param title
     *            the value for job_activityplan.title
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.target
     *
     * @return the value of job_activityplan.target
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.target
     *
     * @param target
     *            the value for job_activityplan.target
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.ideology
     *
     * @return the value of job_activityplan.ideology
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public String getIdeology() {
        return ideology;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.ideology
     *
     * @param ideology
     *            the value for job_activityplan.ideology
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setIdeology(String ideology) {
        this.ideology = ideology;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.content
     *
     * @return the value of job_activityplan.content
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.content
     *
     * @param content
     *            the value for job_activityplan.content
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.auditext
     *
     * @return the value of job_activityplan.auditext
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public String getAuditext() {
        return auditext;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.auditext
     *
     * @param auditext
     *            the value for job_activityplan.auditext
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setAuditext(String auditext) {
        this.auditext = auditext;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.jobmainpoint
     *
     * @return the value of job_activityplan.jobmainpoint
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public String getJobmainpoint() {
        return jobmainpoint;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.jobmainpoint
     *
     * @param jobmainpoint
     *            the value for job_activityplan.jobmainpoint
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setJobmainpoint(String jobmainpoint) {
        this.jobmainpoint = jobmainpoint;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.arrange
     *
     * @return the value of job_activityplan.arrange
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public String getArrange() {
        return arrange;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.arrange
     *
     * @param arrange
     *            the value for job_activityplan.arrange
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setArrange(String arrange) {
        this.arrange = arrange;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_activityplan.guarantee
     *
     * @return the value of job_activityplan.guarantee
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public String getGuarantee() {
        return guarantee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_activityplan.guarantee
     *
     * @param guarantee
     *            the value for job_activityplan.guarantee
     * @mbggenerated Thu Jul 09 22:26:06 CST 2015
     */
    public void setGuarantee(String guarantee) {
        this.guarantee = guarantee;
    }

    public boolean isCanAudit() {
        return canAudit;
    }

    public void setCanAudit(boolean canAudit) {
        this.canAudit = canAudit;
    }

}