package com.njpes.www.entity.workschedule;

public class JobCongressWithBLOBs extends JobCongress {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_congress.subject
     *
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    private String subject;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_congress.persons
     *
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    private String persons;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_congress.content
     *
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_congress.specailrecord
     *
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    //多文本编辑器未用字段，目前多文本编辑器使用content字段
    private String specailrecord;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_congress.otherpersons
     *
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    private String otherpersons;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_congress.subject
     *
     * @return the value of job_congress.subject
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_congress.subject
     *
     * @param subject
     *            the value for job_congress.subject
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_congress.persons
     *
     * @return the value of job_congress.persons
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public String getPersons() {
        return persons;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_congress.persons
     *
     * @param persons
     *            the value for job_congress.persons
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public void setPersons(String persons) {
        this.persons = persons;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_congress.content
     *
     * @return the value of job_congress.content
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_congress.content
     *
     * @param content
     *            the value for job_congress.content
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_congress.specailrecord
     *
     * @return the value of job_congress.specailrecord
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public String getSpecailrecord() {
        return specailrecord;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_congress.specailrecord
     *
     * @param specailrecord
     *            the value for job_congress.specailrecord
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public void setSpecailrecord(String specailrecord) {
        this.specailrecord = specailrecord;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_congress.otherpersons
     *
     * @return the value of job_congress.otherpersons
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public String getOtherpersons() {
        return otherpersons;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_congress.otherpersons
     *
     * @param otherpersons
     *            the value for job_congress.otherpersons
     * @mbggenerated Sun Jul 19 02:00:25 CST 2015
     */
    public void setOtherpersons(String otherpersons) {
        this.otherpersons = otherpersons;
    }

}