package com.njpes.www.entity.workschedule;

import java.io.Serializable;

public class JobNoticeShare implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_notice_share.id
     * 
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_notice_share.notice_id
     * 
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    private Long noticeId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_notice_share.org_id
     * 
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    private Long orgId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_notice_share.send_org_id
     * 
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    private Long sendOrgId;

    private String orgname;

    public String getOrgname() {
        return orgname;
    }

    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_notice_share.id
     * 
     * @return the value of job_notice_share.id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_notice_share.id
     * 
     * @param id
     *            the value for job_notice_share.id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_notice_share.notice_id
     * 
     * @return the value of job_notice_share.notice_id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public Long getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_notice_share.notice_id
     * 
     * @param noticeId
     *            the value for job_notice_share.notice_id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_notice_share.org_id
     * 
     * @return the value of job_notice_share.org_id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_notice_share.org_id
     * 
     * @param orgId
     *            the value for job_notice_share.org_id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_notice_share.send_org_id
     * 
     * @return the value of job_notice_share.send_org_id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public Long getSendOrgId() {
        return sendOrgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_notice_share.send_org_id
     * 
     * @param sendOrgId
     *            the value for job_notice_share.send_org_id
     * @mbggenerated Sat Jun 13 16:44:38 CST 2015
     */
    public void setSendOrgId(Long sendOrgId) {
        this.sendOrgId = sendOrgId;
    }

}
