package com.njpes.www.entity.workschedule;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class JobPlan implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8415406840977915802L;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.id
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.start_time
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Date startTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.end_time
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Date endTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.write_time
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Date writeTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.author
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Long author;

    private String authorName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.dep
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Long dep;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.author_role
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Long authorRole;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.year
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Short year;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.quarter
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Short quarter;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.audit_time
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Date auditTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.auditor
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Long auditor;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.state
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private String state;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan.vip_event
     * 
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    private Boolean vipEvent;

    private String staname;

    private List<JobPlanShare> jobPlanShareList;

    private String[] fileuuids;

    private String schoolyear;

    private String term;

    public String getSchoolyear() {
        return schoolyear;
    }

    public void setSchoolyear(String schoolyear) {
        this.schoolyear = schoolyear;
    }

    public String getTerm() {
        return term;
    }

    public void setTerm(String term) {
        this.term = term;
    }

    public String[] getFileuuids() {
        return fileuuids;
    }

    public void setFileuuids(String[] fileuuids) {
        this.fileuuids = fileuuids;
    }

    public List<JobPlanShare> getJobPlanShareList() {
        return jobPlanShareList;
    }

    public void setJobPlanShareList(List<JobPlanShare> jobPlanShareList) {
        this.jobPlanShareList = jobPlanShareList;
    }

    public String getStaname() {
        return staname;
    }

    public void setStaname(String staname) {
        this.staname = staname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.id
     * 
     * @return the value of job_plan.id
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.id
     * 
     * @param id
     *            the value for job_plan.id
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    public String getAuthorName() {
        return authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.start_time
     * 
     * @return the value of job_plan.start_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.start_time
     * 
     * @param startTime
     *            the value for job_plan.start_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.end_time
     * 
     * @return the value of job_plan.end_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.end_time
     * 
     * @param endTime
     *            the value for job_plan.end_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.write_time
     * 
     * @return the value of job_plan.write_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Date getWriteTime() {
        return writeTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.write_time
     * 
     * @param writeTime
     *            the value for job_plan.write_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setWriteTime(Date writeTime) {
        this.writeTime = writeTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.author
     * 
     * @return the value of job_plan.author
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Long getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.author
     * 
     * @param author
     *            the value for job_plan.author
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setAuthor(Long author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.dep
     * 
     * @return the value of job_plan.dep
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Long getDep() {
        return dep;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.dep
     * 
     * @param dep
     *            the value for job_plan.dep
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setDep(Long dep) {
        this.dep = dep;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.author_role
     * 
     * @return the value of job_plan.author_role
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Long getAuthorRole() {
        return authorRole;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.author_role
     * 
     * @param authorRole
     *            the value for job_plan.author_role
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setAuthorRole(Long authorRole) {
        this.authorRole = authorRole;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.year
     * 
     * @return the value of job_plan.year
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.year
     * 
     * @param year
     *            the value for job_plan.year
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setYear(Short year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.quarter
     * 
     * @return the value of job_plan.quarter
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Short getQuarter() {
        return quarter;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.quarter
     * 
     * @param quarter
     *            the value for job_plan.quarter
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setQuarter(Short quarter) {
        this.quarter = quarter;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.audit_time
     * 
     * @return the value of job_plan.audit_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.audit_time
     * 
     * @param auditTime
     *            the value for job_plan.audit_time
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.auditor
     * 
     * @return the value of job_plan.auditor
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Long getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.auditor
     * 
     * @param auditor
     *            the value for job_plan.auditor
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setAuditor(Long auditor) {
        this.auditor = auditor;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.state
     * 
     * @return the value of job_plan.state
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.state
     * 
     * @param state
     *            the value for job_plan.state
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan.vip_event
     * 
     * @return the value of job_plan.vip_event
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public Boolean getVipEvent() {
        return vipEvent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan.vip_event
     * 
     * @param vipEvent
     *            the value for job_plan.vip_event
     * @mbggenerated Wed Jul 01 00:28:08 CST 2015
     */
    public void setVipEvent(Boolean vipEvent) {
        this.vipEvent = vipEvent;
    }
}