package com.njpes.www.entity.workschedule;

public class JobPlanShare {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan_share.id
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan_share.plan_id
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    private Long planId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan_share.org_id
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    private Long orgId;

    private String orgname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job_plan_share.send_org_id
     *
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    private Long sendOrgId;

    public String getOrgname() {
        return orgname;
    }

    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan_share.id
     *
     * @return the value of job_plan_share.id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan_share.id
     *
     * @param id
     *            the value for job_plan_share.id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan_share.plan_id
     *
     * @return the value of job_plan_share.plan_id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan_share.plan_id
     *
     * @param planId
     *            the value for job_plan_share.plan_id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan_share.org_id
     *
     * @return the value of job_plan_share.org_id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan_share.org_id
     *
     * @param orgId
     *            the value for job_plan_share.org_id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job_plan_share.send_org_id
     *
     * @return the value of job_plan_share.send_org_id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public Long getSendOrgId() {
        return sendOrgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job_plan_share.send_org_id
     *
     * @param sendOrgId
     *            the value for job_plan_share.send_org_id
     * @mbggenerated Sun Jul 05 00:05:26 CST 2015
     */
    public void setSendOrgId(Long sendOrgId) {
        this.sendOrgId = sendOrgId;
    }
}