package com.njpes.www.entity.scaletoollib;

import java.io.Serializable;
import java.util.Date;

public class ExamresultIndividual implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_individual.id
     *
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_individual.parent_id
     *
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_individual.scale_id
     *
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    private Integer scaleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_individual.ok_time
     *
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    private Date okTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_individual.start_time
     *
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_individual.warning_grade
     *
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    private Integer warningGrade;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_individual.valid_val
     *
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    private Integer validVal;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_individual.id
     *
     * @return the value of examresult_individual.id
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_individual.id
     *
     * @param id
     *            the value for examresult_individual.id
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_individual.parent_id
     *
     * @return the value of examresult_individual.parent_id
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_individual.parent_id
     *
     * @param parentId
     *            the value for examresult_individual.parent_id
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_individual.scale_id
     *
     * @return the value of examresult_individual.scale_id
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public Integer getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_individual.scale_id
     *
     * @param scaleId
     *            the value for examresult_individual.scale_id
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public void setScaleId(Integer scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_individual.ok_time
     *
     * @return the value of examresult_individual.ok_time
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public Date getOkTime() {
        return okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_individual.ok_time
     *
     * @param okTime
     *            the value for examresult_individual.ok_time
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public void setOkTime(Date okTime) {
        this.okTime = okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_individual.start_time
     *
     * @return the value of examresult_individual.start_time
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_individual.start_time
     *
     * @param startTime
     *            the value for examresult_individual.start_time
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_individual.warning_grade
     *
     * @return the value of examresult_individual.warning_grade
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public Integer getWarningGrade() {
        return warningGrade;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_individual.warning_grade
     *
     * @param warningGrade
     *            the value for examresult_individual.warning_grade
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public void setWarningGrade(Integer warningGrade) {
        this.warningGrade = warningGrade;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_individual.valid_val
     *
     * @return the value of examresult_individual.valid_val
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public Integer getValidVal() {
        return validVal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_individual.valid_val
     *
     * @param validVal
     *            the value for examresult_individual.valid_val
     * @mbggenerated Sat Mar 21 23:18:02 CST 2015
     */
    public void setValidVal(Integer validVal) {
        this.validVal = validVal;
    }
}