package com.njpes.www.entity.scaletoollib;

import java.io.Serializable;

public class ExamresultDimMentalHealthKey implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.result_id
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Long resultId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.scale_id
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Integer scaleId;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.result_id
     *
     * @return the value of examresult_dim_mental_health.result_id
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Long getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.result_id
     *
     * @param resultId
     *            the value for examresult_dim_mental_health.result_id
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setResultId(Long resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.scale_id
     *
     * @return the value of examresult_dim_mental_health.scale_id
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Integer getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.scale_id
     *
     * @param scaleId
     *            the value for examresult_dim_mental_health.scale_id
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setScaleId(Integer scaleId) {
        this.scaleId = scaleId;
    }
}