package com.njpes.www.entity.scaletoollib;

public class ExamresultDimMentalHealth extends ExamresultDimMentalHealthKey {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w0
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w0;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w1
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w2
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w3
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w3;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w4
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w4;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w5
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w5;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w6
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w6;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w7
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w7;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w8
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w8;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w9
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w9;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w10
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w10;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w11
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w11;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w12
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w12;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w13
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w13;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w14
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w14;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_mental_health.w15
     *
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    private Short w15;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w0
     *
     * @return the value of examresult_dim_mental_health.w0
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW0() {
        return w0;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w0
     *
     * @param w0
     *            the value for examresult_dim_mental_health.w0
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW0(Short w0) {
        this.w0 = w0;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w1
     *
     * @return the value of examresult_dim_mental_health.w1
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW1() {
        return w1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w1
     *
     * @param w1
     *            the value for examresult_dim_mental_health.w1
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW1(Short w1) {
        this.w1 = w1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w2
     *
     * @return the value of examresult_dim_mental_health.w2
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW2() {
        return w2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w2
     *
     * @param w2
     *            the value for examresult_dim_mental_health.w2
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW2(Short w2) {
        this.w2 = w2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w3
     *
     * @return the value of examresult_dim_mental_health.w3
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW3() {
        return w3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w3
     *
     * @param w3
     *            the value for examresult_dim_mental_health.w3
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW3(Short w3) {
        this.w3 = w3;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w4
     *
     * @return the value of examresult_dim_mental_health.w4
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW4() {
        return w4;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w4
     *
     * @param w4
     *            the value for examresult_dim_mental_health.w4
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW4(Short w4) {
        this.w4 = w4;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w5
     *
     * @return the value of examresult_dim_mental_health.w5
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW5() {
        return w5;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w5
     *
     * @param w5
     *            the value for examresult_dim_mental_health.w5
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW5(Short w5) {
        this.w5 = w5;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w6
     *
     * @return the value of examresult_dim_mental_health.w6
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW6() {
        return w6;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w6
     *
     * @param w6
     *            the value for examresult_dim_mental_health.w6
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW6(Short w6) {
        this.w6 = w6;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w7
     *
     * @return the value of examresult_dim_mental_health.w7
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW7() {
        return w7;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w7
     *
     * @param w7
     *            the value for examresult_dim_mental_health.w7
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW7(Short w7) {
        this.w7 = w7;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w8
     *
     * @return the value of examresult_dim_mental_health.w8
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW8() {
        return w8;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w8
     *
     * @param w8
     *            the value for examresult_dim_mental_health.w8
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW8(Short w8) {
        this.w8 = w8;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w9
     *
     * @return the value of examresult_dim_mental_health.w9
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW9() {
        return w9;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w9
     *
     * @param w9
     *            the value for examresult_dim_mental_health.w9
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW9(Short w9) {
        this.w9 = w9;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w10
     *
     * @return the value of examresult_dim_mental_health.w10
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW10() {
        return w10;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w10
     *
     * @param w10
     *            the value for examresult_dim_mental_health.w10
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW10(Short w10) {
        this.w10 = w10;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w11
     *
     * @return the value of examresult_dim_mental_health.w11
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW11() {
        return w11;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w11
     *
     * @param w11
     *            the value for examresult_dim_mental_health.w11
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW11(Short w11) {
        this.w11 = w11;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w12
     *
     * @return the value of examresult_dim_mental_health.w12
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW12() {
        return w12;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w12
     *
     * @param w12
     *            the value for examresult_dim_mental_health.w12
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW12(Short w12) {
        this.w12 = w12;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w13
     *
     * @return the value of examresult_dim_mental_health.w13
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW13() {
        return w13;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w13
     *
     * @param w13
     *            the value for examresult_dim_mental_health.w13
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW13(Short w13) {
        this.w13 = w13;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w14
     *
     * @return the value of examresult_dim_mental_health.w14
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW14() {
        return w14;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w14
     *
     * @param w14
     *            the value for examresult_dim_mental_health.w14
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW14(Short w14) {
        this.w14 = w14;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_mental_health.w15
     *
     * @return the value of examresult_dim_mental_health.w15
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public Short getW15() {
        return w15;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_mental_health.w15
     *
     * @param w15
     *            the value for examresult_dim_mental_health.w15
     * @mbggenerated Sat Mar 21 23:16:22 CST 2015
     */
    public void setW15(Short w15) {
        this.w15 = w15;
    }
}