package com.njpes.www.entity.scaletoollib;

import java.io.Serializable;

public class ScalenormKey implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_norm.grade_order_id
     *
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    private Byte gradeOrderId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_norm.gender
     *
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_norm.scale_id
     *
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    private Integer scaleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_norm.w_id
     *
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    private String wId;

    private int orglevel;
    private int areaid;
    private int type;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_norm.grade_order_id
     *
     * @return the value of scale_norm.grade_order_id
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public Byte getGradeOrderId() {
        return gradeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_norm.grade_order_id
     *
     * @param gradeOrderId
     *            the value for scale_norm.grade_order_id
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public void setGradeOrderId(Byte gradeOrderId) {
        this.gradeOrderId = gradeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_norm.gender
     *
     * @return the value of scale_norm.gender
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_norm.gender
     *
     * @param gender
     *            the value for scale_norm.gender
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_norm.scale_id
     *
     * @return the value of scale_norm.scale_id
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public Integer getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_norm.scale_id
     *
     * @param scaleId
     *            the value for scale_norm.scale_id
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public void setScaleId(Integer scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_norm.w_id
     *
     * @return the value of scale_norm.w_id
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public String getwId() {
        return wId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_norm.w_id
     *
     * @param wId
     *            the value for scale_norm.w_id
     * @mbggenerated Sat Mar 21 23:14:36 CST 2015
     */
    public void setwId(String wId) {
        this.wId = wId;
    }

    public int getOrglevel() {
        return orglevel;
    }

    public void setOrglevel(int orglevel) {
        this.orglevel = orglevel;
    }

    public int getAreaid() {
        return areaid;
    }

    public void setAreaid(int areaid) {
        this.areaid = areaid;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

}