package com.njpes.www.entity.scaletoollib;

import java.io.Serializable;
import java.math.BigDecimal;

public class Scalewarning implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.id
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.scale_id
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private String scaleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.wid
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.wlevel
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private Integer wlevel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.z
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private Byte z;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.w1
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private BigDecimal w1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.w2
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private BigDecimal w2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_warning.w3
     *
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    private BigDecimal w3;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.id
     *
     * @return the value of scale_warning.id
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.id
     *
     * @param id
     *            the value for scale_warning.id
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.scale_id
     *
     * @return the value of scale_warning.scale_id
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public String getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.scale_id
     *
     * @param scaleId
     *            the value for scale_warning.scale_id
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setScaleId(String scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.wid
     *
     * @return the value of scale_warning.wid
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.wid
     *
     * @param wid
     *            the value for scale_warning.wid
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.wlevel
     *
     * @return the value of scale_warning.wlevel
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public Integer getWlevel() {
        return wlevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.wlevel
     *
     * @param wlevel
     *            the value for scale_warning.wlevel
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setWlevel(Integer wlevel) {
        this.wlevel = wlevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.z
     *
     * @return the value of scale_warning.z
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public Byte getZ() {
        return z;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.z
     *
     * @param z
     *            the value for scale_warning.z
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setZ(Byte z) {
        this.z = z;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.w1
     *
     * @return the value of scale_warning.w1
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public BigDecimal getW1() {
        return w1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.w1
     *
     * @param w1
     *            the value for scale_warning.w1
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setW1(BigDecimal w1) {
        this.w1 = w1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.w2
     *
     * @return the value of scale_warning.w2
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public BigDecimal getW2() {
        return w2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.w2
     *
     * @param w2
     *            the value for scale_warning.w2
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setW2(BigDecimal w2) {
        this.w2 = w2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_warning.w3
     *
     * @return the value of scale_warning.w3
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public BigDecimal getW3() {
        return w3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_warning.w3
     *
     * @param w3
     *            the value for scale_warning.w3
     * @mbggenerated Sat Mar 21 23:15:25 CST 2015
     */
    public void setW3(BigDecimal w3) {
        this.w3 = w3;
    }
}