package com.njpes.www.entity.scaletoollib;

import java.io.Serializable;
import java.util.Date;

public class Scale implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.id
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.code
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.title
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.shortname
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.typeid
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Byte typeid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.assesstype
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer assesstype;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.dimensions
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private String dimensions;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.source
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.creationtime
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Date creationtime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.flag
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.questionnum
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer questionnum;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.startage
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer startage;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.endage
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer endage;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.grade_id
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer gradeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.reportchart
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private String reportchart;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.prewarn
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Byte prewarn;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.totalscore
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Byte totalscore;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.examtime
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private Integer examtime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale.xmlstr
     *
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    private String xmlstr;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.id
     *
     * @return the value of scale.id
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */

    private String showtitle;

    public String getShowtitle() {
        return showtitle;
    }

    public void setShowtitle(String showtitle) {
        this.showtitle = showtitle;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.id
     *
     * @param id
     *            the value for scale.id
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.code
     *
     * @return the value of scale.code
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.code
     *
     * @param code
     *            the value for scale.code
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.title
     *
     * @return the value of scale.title
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.title
     *
     * @param title
     *            the value for scale.title
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.shortname
     *
     * @return the value of scale.shortname
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.shortname
     *
     * @param shortname
     *            the value for scale.shortname
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.typeid
     *
     * @return the value of scale.typeid
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Byte getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.typeid
     *
     * @param typeid
     *            the value for scale.typeid
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setTypeid(Byte typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.assesstype
     *
     * @return the value of scale.assesstype
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getAssesstype() {
        return assesstype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.assesstype
     *
     * @param assesstype
     *            the value for scale.assesstype
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setAssesstype(Integer assesstype) {
        this.assesstype = assesstype;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.dimensions
     *
     * @return the value of scale.dimensions
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public String getDimensions() {
        return dimensions;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.dimensions
     *
     * @param dimensions
     *            the value for scale.dimensions
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setDimensions(String dimensions) {
        this.dimensions = dimensions;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.source
     *
     * @return the value of scale.source
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.source
     *
     * @param source
     *            the value for scale.source
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.creationtime
     *
     * @return the value of scale.creationtime
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.creationtime
     *
     * @param creationtime
     *            the value for scale.creationtime
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.flag
     *
     * @return the value of scale.flag
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.flag
     *
     * @param flag
     *            the value for scale.flag
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.questionnum
     *
     * @return the value of scale.questionnum
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getQuestionnum() {
        return questionnum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.questionnum
     *
     * @param questionnum
     *            the value for scale.questionnum
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setQuestionnum(Integer questionnum) {
        this.questionnum = questionnum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.startage
     *
     * @return the value of scale.startage
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getStartage() {
        return startage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.startage
     *
     * @param startage
     *            the value for scale.startage
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setStartage(Integer startage) {
        this.startage = startage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.endage
     *
     * @return the value of scale.endage
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getEndage() {
        return endage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.endage
     *
     * @param endage
     *            the value for scale.endage
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setEndage(Integer endage) {
        this.endage = endage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.grade_id
     *
     * @return the value of scale.grade_id
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.grade_id
     *
     * @param gradeId
     *            the value for scale.grade_id
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.reportchart
     *
     * @return the value of scale.reportchart
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public String getReportchart() {
        return reportchart;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.reportchart
     *
     * @param reportchart
     *            the value for scale.reportchart
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setReportchart(String reportchart) {
        this.reportchart = reportchart;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.prewarn
     *
     * @return the value of scale.prewarn
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Byte getPrewarn() {
        return prewarn;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.prewarn
     *
     * @param prewarn
     *            the value for scale.prewarn
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setPrewarn(Byte prewarn) {
        this.prewarn = prewarn;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.totalscore
     *
     * @return the value of scale.totalscore
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Byte getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.totalscore
     *
     * @param totalscore
     *            the value for scale.totalscore
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setTotalscore(Byte totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.examtime
     *
     * @return the value of scale.examtime
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public Integer getExamtime() {
        return examtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.examtime
     *
     * @param examtime
     *            the value for scale.examtime
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setExamtime(Integer examtime) {
        this.examtime = examtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale.xmlstr
     *
     * @return the value of scale.xmlstr
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public String getXmlstr() {
        return xmlstr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale.xmlstr
     *
     * @param xmlstr
     *            the value for scale.xmlstr
     * @mbggenerated Sat Mar 21 23:13:00 CST 2015
     */
    public void setXmlstr(String xmlstr) {
        this.xmlstr = xmlstr;
    }
}