package com.njpes.www.entity.scaletoollib;

import java.io.Serializable;
import java.math.BigDecimal;

public class Scalescoregrade implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.id
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.scale_id
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private String scaleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.wid
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.wlevel
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private Integer wlevel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.z
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private Byte z;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.score1
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private BigDecimal score1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.score2
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private BigDecimal score2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.score3
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private BigDecimal score3;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column scale_scoregrade.score4
     *
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    private BigDecimal score4;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.id
     *
     * @return the value of scale_scoregrade.id
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.id
     *
     * @param id
     *            the value for scale_scoregrade.id
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.scale_id
     *
     * @return the value of scale_scoregrade.scale_id
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public String getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.scale_id
     *
     * @param scaleId
     *            the value for scale_scoregrade.scale_id
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setScaleId(String scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.wid
     *
     * @return the value of scale_scoregrade.wid
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.wid
     *
     * @param wid
     *            the value for scale_scoregrade.wid
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.wlevel
     *
     * @return the value of scale_scoregrade.wlevel
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public Integer getWlevel() {
        return wlevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.wlevel
     *
     * @param wlevel
     *            the value for scale_scoregrade.wlevel
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setWlevel(Integer wlevel) {
        this.wlevel = wlevel;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.z
     *
     * @return the value of scale_scoregrade.z
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public Byte getZ() {
        return z;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.z
     *
     * @param z
     *            the value for scale_scoregrade.z
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setZ(Byte z) {
        this.z = z;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.score1
     *
     * @return the value of scale_scoregrade.score1
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public BigDecimal getScore1() {
        return score1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.score1
     *
     * @param score1
     *            the value for scale_scoregrade.score1
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setScore1(BigDecimal score1) {
        this.score1 = score1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.score2
     *
     * @return the value of scale_scoregrade.score2
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public BigDecimal getScore2() {
        return score2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.score2
     *
     * @param score2
     *            the value for scale_scoregrade.score2
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setScore2(BigDecimal score2) {
        this.score2 = score2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.score3
     *
     * @return the value of scale_scoregrade.score3
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public BigDecimal getScore3() {
        return score3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.score3
     *
     * @param score3
     *            the value for scale_scoregrade.score3
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setScore3(BigDecimal score3) {
        this.score3 = score3;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column scale_scoregrade.score4
     *
     * @return the value of scale_scoregrade.score4
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public BigDecimal getScore4() {
        return score4;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column scale_scoregrade.score4
     *
     * @param score4
     *            the value for scale_scoregrade.score4
     * @mbggenerated Sat Mar 21 23:15:05 CST 2015
     */
    public void setScore4(BigDecimal score4) {
        this.score4 = score4;
    }
}