package com.njpes.www.entity.scaletoollib;

public class StatConfig {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_param.id
     *
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_param.title
     *
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_param.stat_type
     *
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    private Integer statType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_param.stat_class
     *
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    private String statClass;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column stat_param.id
     *
     * @return the value of stat_param.id
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column stat_param.id
     *
     * @param id
     *            the value for stat_param.id
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column stat_param.title
     *
     * @return the value of stat_param.title
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column stat_param.title
     *
     * @param title
     *            the value for stat_param.title
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column stat_param.stat_type
     *
     * @return the value of stat_param.stat_type
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public Integer getStatType() {
        return statType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column stat_param.stat_type
     *
     * @param statType
     *            the value for stat_param.stat_type
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public void setStatType(Integer statType) {
        this.statType = statType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column stat_param.stat_class
     *
     * @return the value of stat_param.stat_class
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public String getStatClass() {
        return statClass;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column stat_param.stat_class
     *
     * @param statClass
     *            the value for stat_param.stat_class
     * @mbggenerated Wed Sep 02 22:12:51 CST 2015
     */
    public void setStatClass(String statClass) {
        this.statClass = statClass;
    }
}