package com.njpes.www.entity.scaletoollib;

import java.io.Serializable;

import org.springframework.stereotype.Component;

@Component
public class StatExamResultTask implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_columns.id
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    private Long taskid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_columns.table_name
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_columns.col_name
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_columns.col_type
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_columns.dic_table_name
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column stat_columns.col_title
     *
     * @mbggenerated Sat Sep 05 17:13:08 CST 2015
     */

    public Long getTaskid() {
        return taskid;
    }

    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    public String getTaskname() {
        return taskname;
    }

    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }
}