package com.njpes.www.entity.scaletoollib;

import java.util.Date;

public class TeacherDimExamResult {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.result_id
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Long resultId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.user_id
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.scale_id
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Integer scaleId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.org_id
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Long orgId;

    private Byte gender;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.ok_time
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Date okTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w0
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w0;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w1
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w1;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w2
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w2;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w3
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w3;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w4
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w4;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w5
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w5;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w6
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w6;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w7
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w7;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w8
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w8;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w9
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w9;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w10
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w10;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w11
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w11;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w12
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w12;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w13
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w13;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w14
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w14;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w15
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w15;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w16
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w16;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w17
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w17;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w18
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w18;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w19
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w19;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w20
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w20;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w21
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w21;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w22
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w22;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w23
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w23;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w24
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w24;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examresult_dim_teacher.w25
     *
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    private Short w25;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.result_id
     *
     * @return the value of examresult_dim_teacher.result_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Long getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.result_id
     *
     * @param resultId
     *            the value for examresult_dim_teacher.result_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setResultId(Long resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.user_id
     *
     * @return the value of examresult_dim_teacher.user_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.user_id
     *
     * @param userId
     *            the value for examresult_dim_teacher.user_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.scale_id
     *
     * @return the value of examresult_dim_teacher.scale_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Integer getScaleId() {
        return scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.scale_id
     *
     * @param scaleId
     *            the value for examresult_dim_teacher.scale_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setScaleId(Integer scaleId) {
        this.scaleId = scaleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.org_id
     *
     * @return the value of examresult_dim_teacher.org_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.org_id
     *
     * @param orgId
     *            the value for examresult_dim_teacher.org_id
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.gender
     *
     * @return the value of examresult_dim_teacher.gender
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.gender
     *
     * @param gender
     *            the value for examresult_dim_teacher.gender
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.ok_time
     *
     * @return the value of examresult_dim_teacher.ok_time
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Date getOkTime() {
        return okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.ok_time
     *
     * @param okTime
     *            the value for examresult_dim_teacher.ok_time
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setOkTime(Date okTime) {
        this.okTime = okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w0
     *
     * @return the value of examresult_dim_teacher.w0
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW0() {
        return w0;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w0
     *
     * @param w0
     *            the value for examresult_dim_teacher.w0
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW0(Short w0) {
        this.w0 = w0;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w1
     *
     * @return the value of examresult_dim_teacher.w1
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW1() {
        return w1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w1
     *
     * @param w1
     *            the value for examresult_dim_teacher.w1
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW1(Short w1) {
        this.w1 = w1;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w2
     *
     * @return the value of examresult_dim_teacher.w2
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW2() {
        return w2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w2
     *
     * @param w2
     *            the value for examresult_dim_teacher.w2
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW2(Short w2) {
        this.w2 = w2;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w3
     *
     * @return the value of examresult_dim_teacher.w3
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW3() {
        return w3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w3
     *
     * @param w3
     *            the value for examresult_dim_teacher.w3
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW3(Short w3) {
        this.w3 = w3;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w4
     *
     * @return the value of examresult_dim_teacher.w4
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW4() {
        return w4;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w4
     *
     * @param w4
     *            the value for examresult_dim_teacher.w4
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW4(Short w4) {
        this.w4 = w4;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w5
     *
     * @return the value of examresult_dim_teacher.w5
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW5() {
        return w5;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w5
     *
     * @param w5
     *            the value for examresult_dim_teacher.w5
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW5(Short w5) {
        this.w5 = w5;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w6
     *
     * @return the value of examresult_dim_teacher.w6
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW6() {
        return w6;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w6
     *
     * @param w6
     *            the value for examresult_dim_teacher.w6
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW6(Short w6) {
        this.w6 = w6;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w7
     *
     * @return the value of examresult_dim_teacher.w7
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW7() {
        return w7;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w7
     *
     * @param w7
     *            the value for examresult_dim_teacher.w7
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW7(Short w7) {
        this.w7 = w7;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w8
     *
     * @return the value of examresult_dim_teacher.w8
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW8() {
        return w8;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w8
     *
     * @param w8
     *            the value for examresult_dim_teacher.w8
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW8(Short w8) {
        this.w8 = w8;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w9
     *
     * @return the value of examresult_dim_teacher.w9
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW9() {
        return w9;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w9
     *
     * @param w9
     *            the value for examresult_dim_teacher.w9
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW9(Short w9) {
        this.w9 = w9;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w10
     *
     * @return the value of examresult_dim_teacher.w10
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW10() {
        return w10;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w10
     *
     * @param w10
     *            the value for examresult_dim_teacher.w10
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW10(Short w10) {
        this.w10 = w10;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w11
     *
     * @return the value of examresult_dim_teacher.w11
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW11() {
        return w11;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w11
     *
     * @param w11
     *            the value for examresult_dim_teacher.w11
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW11(Short w11) {
        this.w11 = w11;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w12
     *
     * @return the value of examresult_dim_teacher.w12
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW12() {
        return w12;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w12
     *
     * @param w12
     *            the value for examresult_dim_teacher.w12
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW12(Short w12) {
        this.w12 = w12;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w13
     *
     * @return the value of examresult_dim_teacher.w13
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW13() {
        return w13;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w13
     *
     * @param w13
     *            the value for examresult_dim_teacher.w13
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW13(Short w13) {
        this.w13 = w13;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w14
     *
     * @return the value of examresult_dim_teacher.w14
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW14() {
        return w14;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w14
     *
     * @param w14
     *            the value for examresult_dim_teacher.w14
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW14(Short w14) {
        this.w14 = w14;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w15
     *
     * @return the value of examresult_dim_teacher.w15
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW15() {
        return w15;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w15
     *
     * @param w15
     *            the value for examresult_dim_teacher.w15
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW15(Short w15) {
        this.w15 = w15;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w16
     *
     * @return the value of examresult_dim_teacher.w16
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW16() {
        return w16;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w16
     *
     * @param w16
     *            the value for examresult_dim_teacher.w16
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW16(Short w16) {
        this.w16 = w16;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w17
     *
     * @return the value of examresult_dim_teacher.w17
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW17() {
        return w17;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w17
     *
     * @param w17
     *            the value for examresult_dim_teacher.w17
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW17(Short w17) {
        this.w17 = w17;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w18
     *
     * @return the value of examresult_dim_teacher.w18
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW18() {
        return w18;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w18
     *
     * @param w18
     *            the value for examresult_dim_teacher.w18
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW18(Short w18) {
        this.w18 = w18;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w19
     *
     * @return the value of examresult_dim_teacher.w19
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW19() {
        return w19;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w19
     *
     * @param w19
     *            the value for examresult_dim_teacher.w19
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW19(Short w19) {
        this.w19 = w19;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w20
     *
     * @return the value of examresult_dim_teacher.w20
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW20() {
        return w20;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w20
     *
     * @param w20
     *            the value for examresult_dim_teacher.w20
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW20(Short w20) {
        this.w20 = w20;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w21
     *
     * @return the value of examresult_dim_teacher.w21
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW21() {
        return w21;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w21
     *
     * @param w21
     *            the value for examresult_dim_teacher.w21
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW21(Short w21) {
        this.w21 = w21;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w22
     *
     * @return the value of examresult_dim_teacher.w22
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW22() {
        return w22;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w22
     *
     * @param w22
     *            the value for examresult_dim_teacher.w22
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW22(Short w22) {
        this.w22 = w22;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w23
     *
     * @return the value of examresult_dim_teacher.w23
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW23() {
        return w23;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w23
     *
     * @param w23
     *            the value for examresult_dim_teacher.w23
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW23(Short w23) {
        this.w23 = w23;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w24
     *
     * @return the value of examresult_dim_teacher.w24
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW24() {
        return w24;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w24
     *
     * @param w24
     *            the value for examresult_dim_teacher.w24
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW24(Short w24) {
        this.w24 = w24;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examresult_dim_teacher.w25
     *
     * @return the value of examresult_dim_teacher.w25
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public Short getW25() {
        return w25;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examresult_dim_teacher.w25
     *
     * @param w25
     *            the value for examresult_dim_teacher.w25
     * @mbggenerated Tue Apr 07 09:16:34 CST 2015
     */
    public void setW25(Short w25) {
        this.w25 = w25;
    }
}