package com.njpes.www.dao.consultcenter;

import java.util.List;

import com.njpes.www.entity.consultcenter.Appointment;

public interface AppointmentMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_appointment
     * 
     * @mbggenerated Wed Jun 24 23:27:08 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_appointment
     * 
     * @mbggenerated Wed Jun 24 23:27:08 CST 2015
     */
    int insert(Appointment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_appointment
     * 
     * @mbggenerated Wed Jun 24 23:27:08 CST 2015
     */
    int insertSelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_appointment
     * 
     * @mbggenerated Wed Jun 24 23:27:08 CST 2015
     */
    Appointment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_appointment
     * 
     * @mbggenerated Wed Jun 24 23:27:08 CST 2015
     */
    int updateByPrimaryKeySelective(Appointment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_appointment
     * 
     * @mbggenerated Wed Jun 24 23:27:08 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Appointment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_appointment
     * 
     * @mbggenerated Wed Jun 24 23:27:08 CST 2015
     */
    int updateByPrimaryKey(Appointment record);

    /**
     * @Description:
     * @param ids
     * @return
     */
    List<Appointment> selectListByIds(Long[] ids);

    int deleteByPrimaryKeyWithNext(Long id);
}