package com.njpes.www.dao.consultcenter;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.consultcenter.Email;
import com.njpes.www.utils.PageParameter;

public interface EmailMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_online_email
     * 
     * @mbggenerated Sat Sep 12 10:28:30 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_online_email
     * 
     * @mbggenerated Sat Sep 12 10:28:30 CST 2015
     */
    int insert(Email record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_online_email
     * 
     * @mbggenerated Sat Sep 12 10:28:30 CST 2015
     */
    int insertSelective(Email record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_online_email
     * 
     * @mbggenerated Sat Sep 12 10:28:30 CST 2015
     */
    Email selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_online_email
     * 
     * @mbggenerated Sat Sep 12 10:28:30 CST 2015
     */
    int updateByPrimaryKeySelective(Email record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_online_email
     * 
     * @mbggenerated Sat Sep 12 10:28:30 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Email record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_online_email
     * 
     * @mbggenerated Sat Sep 12 10:28:30 CST 2015
     */
    int updateByPrimaryKey(Email record);

    /**
     * @Description:
     * @param email
     * @param page
     * @param beginDate
     * @param endDate
     * @return
     */
    List<Email> selectEntityByPage(@Param("email") Email email, @Param("page") PageParameter page,
            @Param("beginDate") Date beginDate, @Param("endDate") Date endDate);

    List<Email> selectListByIds(@Param("ids") String[] ids);
}