package com.njpes.www.dao.consultcenter;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.consultcenter.Scheduling;
import com.njpes.www.utils.PageParameter;

public interface SchedulingMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_scheduling
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_scheduling
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    int insert(Scheduling record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_scheduling
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    int insertSelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_scheduling
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    Scheduling selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_scheduling
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    int updateByPrimaryKeySelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_scheduling
     * 
     * @mbggenerated Thu Jun 11 23:37:44 CST 2015
     */
    int updateByPrimaryKey(Scheduling record);

    /**
     * @Description:
     * @param scheduling
     * @param page
     * @param beginDate
     * @param endDate
     * @return
     */
    List<Scheduling> selectListByEntity(@Param("scheduling") Scheduling scheduling, @Param("page") PageParameter page,
            @Param("beginDate") Date beginDate, @Param("endDate") Date endDate);

    /**
     * @Description:
     * @param scheduling
     * @return
     */
    int delByEntity(Scheduling scheduling);
}