package com.njpes.www.dao.consultcenter;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.consultcenter.Team;
import com.njpes.www.utils.PageParameter;

public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_team
     * 
     * @mbggenerated Wed May 27 20:29:35 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_team
     * 
     * @mbggenerated Wed May 27 20:29:35 CST 2015
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_team
     * 
     * @mbggenerated Wed May 27 20:29:35 CST 2015
     */
    int insertSelective(Team record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_team
     * 
     * @mbggenerated Wed May 27 20:29:35 CST 2015
     */
    Team selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_team
     * 
     * @mbggenerated Wed May 27 20:29:35 CST 2015
     */
    int updateByPrimaryKeySelective(Team record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_team
     * 
     * @mbggenerated Wed May 27 20:29:35 CST 2015
     */
    int updateByPrimaryKey(Team record);

    /**
     * @Description:
     * @param team
     * @param page
     * @return
     */
    List<Team> selectEntityByPage(@Param("team") Team team, @Param("page") PageParameter page);
}