package com.njpes.www.dao.consultcenter;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.consultcenter.WarningStudent;
import com.njpes.www.utils.PageParameter;

public interface WarningStudentMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table view_warning_student
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    int insert(WarningStudent record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table view_warning_student
     * 
     * @mbggenerated Sun Jul 05 15:46:18 CST 2015
     */
    int insertSelective(WarningStudent record);

    /**
     * @Description:
     * @param warningStudent
     * @param page
     * @param beginDate
     * @param endDate
     * @return
     */
    List<WarningStudent> selectEntityByPage(@Param("warningStudent") WarningStudent warningStudent,
            @Param("page") PageParameter page, @Param("beginDate") Date beginDate, @Param("endDate") Date endDate);
}