package com.njpes.www.dao.consultcenter;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.consultcenter.WarningTeacher;
import com.njpes.www.utils.PageParameter;

public interface WarningTeacherMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table view_warning_teacher
     * 
     * @mbggenerated Sun Jul 05 15:45:51 CST 2015
     */
    int insert(WarningTeacher record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table view_warning_teacher
     * 
     * @mbggenerated Sun Jul 05 15:45:51 CST 2015
     */
    int insertSelective(WarningTeacher record);

    /**
     * @Description:
     * @param warningTeacher
     * @param object
     * @param object2
     * @param object3
     * @return
     */
    List<WarningTeacher> selectEntityByPage(@Param("warningTeacher") WarningTeacher warningTeacher,
            @Param("page") PageParameter page, @Param("beginDate") Date beginDate, @Param("endDate") Date endDate);
}