package com.njpes.www.dao.consultcenter;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.consultcenter.WarningInterveneS;
import com.njpes.www.entity.consultcenter.WarningInterveneSWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface WarningInterveneSMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_student
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_student
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    int insert(WarningInterveneSWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_student
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    int insertSelective(WarningInterveneSWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_student
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    WarningInterveneSWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_student
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    int updateByPrimaryKeySelective(WarningInterveneSWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_student
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(WarningInterveneSWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_student
     * 
     * @mbggenerated Sat Nov 28 15:06:49 CST 2015
     */
    int updateByPrimaryKey(WarningInterveneS record);

    /**
     * @Description:
     * @param warningInterveneS
     * @param page
     * @param beginDate
     * @param endDate
     * @return
     */
    List<WarningInterveneS> selectEntityByPage(@Param("warningInterveneS") WarningInterveneS warningInterveneS,
            @Param("page") PageParameter page, @Param("beginDate") Date beginDate, @Param("endDate") Date endDate,
            @Param("step") int step);

    List<WarningInterveneSWithBLOBs> selectEntityBLOBsByPage(
            @Param("warningInterveneS") WarningInterveneSWithBLOBs warningInterveneS, @Param("page") PageParameter page,
            @Param("beginDate") Date beginDate, @Param("endDate") Date endDate, @Param("step") int step);

}