package com.njpes.www.dao.consultcenter;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.consultcenter.WarningInterveneT;
import com.njpes.www.entity.consultcenter.WarningInterveneTWithBLOBs;
import com.njpes.www.utils.PageParameter;

public interface WarningInterveneTMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_teacher
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_teacher
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    int insert(WarningInterveneTWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_teacher
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    int insertSelective(WarningInterveneTWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_teacher
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    WarningInterveneTWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_teacher
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    int updateByPrimaryKeySelective(WarningInterveneTWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_teacher
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(WarningInterveneTWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table coach_warning_teacher
     * 
     * @mbggenerated Sat Nov 28 15:06:15 CST 2015
     */
    int updateByPrimaryKey(WarningInterveneT record);

    /**
     * @Description:
     * @param warningInterveneT
     * @param page
     * @param beginDate
     * @param endDate
     * @return
     */
    List<WarningInterveneT> selectEntityByPage(@Param("warningInterveneT") WarningInterveneT warningInterveneT,
            @Param("page") PageParameter page, @Param("beginDate") Date beginDate, @Param("endDate") Date endDate,
            @Param("step") int step);

    List<WarningInterveneTWithBLOBs> selectEntityBLOBsByPage(
            @Param("warningInterveneT") WarningInterveneTWithBLOBs warningInterveneT, @Param("page") PageParameter page,
            @Param("beginDate") Date beginDate, @Param("endDate") Date endDate, @Param("step") int step);
}