package com.njpes.www.entity.assessmentcenter;

import java.util.Date;

import com.njpes.www.entity.baseinfo.Account;

public class Examdo extends ExamdoKey {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_student.lo_time
     *
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    private Date loTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_student.hi_time
     *
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    private Date hiTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_student.ok_time
     *
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    private Date okTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column examdo_student.flag
     *
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    private Byte flag;

    private Account account;

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    private String scalename;

    public String getScalename() {
        return scalename;
    }

    public void setScalename(String scalename) {
        this.scalename = scalename;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_student.lo_time
     *
     * @return the value of examdo_student.lo_time
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public Date getLoTime() {
        return loTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_student.lo_time
     *
     * @param loTime
     *            the value for examdo_student.lo_time
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public void setLoTime(Date loTime) {
        this.loTime = loTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_student.hi_time
     *
     * @return the value of examdo_student.hi_time
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public Date getHiTime() {
        return hiTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_student.hi_time
     *
     * @param hiTime
     *            the value for examdo_student.hi_time
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public void setHiTime(Date hiTime) {
        this.hiTime = hiTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_student.ok_time
     *
     * @return the value of examdo_student.ok_time
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public Date getOkTime() {
        return okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_student.ok_time
     *
     * @param okTime
     *            the value for examdo_student.ok_time
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public void setOkTime(Date okTime) {
        this.okTime = okTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column examdo_student.flag
     *
     * @return the value of examdo_student.flag
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column examdo_student.flag
     *
     * @param flag
     *            the value for examdo_student.flag
     * @mbggenerated Sun May 17 15:42:20 CST 2015
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }
}