package com.njpes.www.entity.assessmentcenter;

public class InvestReport {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invest_report.id
     *
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invest_report.investdo_id
     *
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    private Integer investdoId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invest_report.question_no
     *
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    private Integer questionNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invest_report.answer_no
     *
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    private Integer answerNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column invest_report.count
     *
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invest_report.id
     *
     * @return the value of invest_report.id
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invest_report.id
     *
     * @param id
     *            the value for invest_report.id
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invest_report.investdo_id
     *
     * @return the value of invest_report.investdo_id
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public Integer getInvestdoId() {
        return investdoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invest_report.investdo_id
     *
     * @param investdoId
     *            the value for invest_report.investdo_id
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public void setInvestdoId(Integer investdoId) {
        this.investdoId = investdoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invest_report.question_no
     *
     * @return the value of invest_report.question_no
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public Integer getQuestionNo() {
        return questionNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invest_report.question_no
     *
     * @param questionNo
     *            the value for invest_report.question_no
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public void setQuestionNo(Integer questionNo) {
        this.questionNo = questionNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invest_report.answer_no
     *
     * @return the value of invest_report.answer_no
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public Integer getAnswerNo() {
        return answerNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invest_report.answer_no
     *
     * @param answerNo
     *            the value for invest_report.answer_no
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public void setAnswerNo(Integer answerNo) {
        this.answerNo = answerNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column invest_report.count
     *
     * @return the value of invest_report.count
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column invest_report.count
     *
     * @param count
     *            the value for invest_report.count
     * @mbggenerated Sun Jun 07 14:36:58 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}