package com.njpes.www.entity.assessmentcenter;

public class InvestdoEdu {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investdo_edu.id
     * 
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investdo_edu.taskid
     * 
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    private Long taskid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investdo_edu.orgid
     * 
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    private Long orgid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investdo_edu.gradeids
     * 
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    private String gradeids;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investdo_edu.roleids
     * 
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    private String roleids;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investdo_edu.flag
     * 
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column investdo_edu.id
     * 
     * @return the value of investdo_edu.id
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column investdo_edu.id
     * 
     * @param id
     *            the value for investdo_edu.id
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column investdo_edu.taskid
     * 
     * @return the value of investdo_edu.taskid
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public Long getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column investdo_edu.taskid
     * 
     * @param taskid
     *            the value for investdo_edu.taskid
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column investdo_edu.orgid
     * 
     * @return the value of investdo_edu.orgid
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public Long getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column investdo_edu.orgid
     * 
     * @param orgid
     *            the value for investdo_edu.orgid
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public void setOrgid(Long orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column investdo_edu.gradeids
     * 
     * @return the value of investdo_edu.gradeids
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public String getGradeids() {
        return gradeids;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column investdo_edu.gradeids
     * 
     * @param gradeids
     *            the value for investdo_edu.gradeids
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public void setGradeids(String gradeids) {
        this.gradeids = gradeids;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column investdo_edu.roleids
     * 
     * @return the value of investdo_edu.roleids
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public String getRoleids() {
        return roleids;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column investdo_edu.roleids
     * 
     * @param roleids
     *            the value for investdo_edu.roleids
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public void setRoleids(String roleids) {
        this.roleids = roleids;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column investdo_edu.flag
     * 
     * @return the value of investdo_edu.flag
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column investdo_edu.flag
     * 
     * @param flag
     *            the value for investdo_edu.flag
     * @mbggenerated Mon Dec 28 23:25:48 CST 2015
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}