package com.njpes.www.entity.assessmentcenter;

import java.util.Date;

public class MyInvesttask {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.id
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.name
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private String taskname;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.scaleid
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private Integer scaleid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.ownerid
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private Date starttime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.endtime
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private Date endtime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.createtime
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private Date createtime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.orgids
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private Integer objecttype;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column investtask.gradeids
     * 
     * @mbggenerated Thu Dec 31 15:49:38 CST 2015
     */
    private Integer roleid;

    private String scalename;
    private Integer resultid;
    private Long taskid;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskname() {
        return taskname;
    }

    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    public Integer getScaleid() {
        return scaleid;
    }

    public void setScaleid(Integer scaleid) {
        this.scaleid = scaleid;
    }

    public Date getStarttime() {
        return starttime;
    }

    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    public Date getEndtime() {
        return endtime;
    }

    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public Integer getObjecttype() {
        return objecttype;
    }

    public void setObjecttype(Integer objecttype) {
        this.objecttype = objecttype;
    }

    public Integer getRoleid() {
        return roleid;
    }

    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    public String getScalename() {
        return scalename;
    }

    public void setScalename(String scalename) {
        this.scalename = scalename;
    }

    public Integer getResultid() {
        return resultid;
    }

    public void setResultid(Integer resultid) {
        this.resultid = resultid;
    }

    public Long getTaskid() {
        return taskid;
    }

    public void setTaskid(Long taskid) {
        this.taskid = taskid;
    }

}