package com.njpes.www.entity.baseinfo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Set;

import com.njpes.www.entity.baseinfo.enums.AcountTypeFlag;

public class Account implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7981795570878253844L;
    public static final int USERNAME_MIN_LENGTH = 2;
    public static final int USERNAME_MAX_LENGTH = 20;
    public static final int PASSWORD_MIN_LENGTH = 5;
    public static final int PASSWORD_MAX_LENGTH = 50;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account.id
     *
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account.username
     *
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account.password
     *
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account.create_time
     *
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account.update_time
     *
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account.role_flag 是学生还是老师还是家长
     * 
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    private Integer typeFlag;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column account.state
     *
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    private Integer state;

    private Integer admin;

    private String theme; // 用户的主题名称

    private String logintype = ""; // 用户登陆类型

    private String realname;

    private int dogid;

    private String isdoglongin;

    public int getDogid() {
        return dogid;
    }

    public void setDogid(int dogid) {
        this.dogid = dogid;
    }

    public String getIsdoglongin() {
        return isdoglongin;
    }

    public void setIsdoglongin(String isdoglongin) {
        this.isdoglongin = isdoglongin;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    private List<AccountOrgJob> organizationJobs;

    /** 用户具有的角色id列表 */
    private Set<Role> roles;
    /** 用户单独授权的资源以及功能 */
    private List<UserResPerm> userResPermsList;

    /** 身份证号信息 */
    private String idcard;

    public List<UserResPerm> getUserResPermsList() {
        return userResPermsList;
    }

    public void setUserResPermsList(List<UserResPerm> userResPermsList) {
        this.userResPermsList = userResPermsList;
    }

    public String getIdcard() {
        return idcard;
    }

    public String getTheme() {
        return theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public Integer getAdmin() {
        return admin;
    }

    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public String getLogintype() {
        return logintype;
    }

    public void setLogintype(String logintype) {
        this.logintype = logintype;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account.id
     *
     * @return the value of account.id
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account.id
     *
     * @param id
     *            the value for account.id
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account.username
     *
     * @return the value of account.username
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account.username
     *
     * @param username
     *            the value for account.username
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account.password
     *
     * @return the value of account.password
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account.password
     *
     * @param password
     *            the value for account.password
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account.create_time
     *
     * @return the value of account.create_time
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account.create_time
     *
     * @param createTime
     *            the value for account.create_time
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account.update_time
     *
     * @return the value of account.update_time
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account.update_time
     *
     * @param updateTime
     *            the value for account.update_time
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account.role_flag
     *
     * @return the value of account.role_flag
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public Integer getTypeFlag() {
        return typeFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account.role_flag
     *
     * @param roleFlag
     *            the value for account.role_flag
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public void setTypeFlag(Integer typeFlag) {
        this.typeFlag = typeFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column account.state
     *
     * @return the value of account.state
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column account.state
     *
     * @param state
     *            the value for account.state
     * @mbggenerated Sat Mar 21 22:47:33 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    public List<AccountOrgJob> getOrganizationJobs() {
        return organizationJobs;
    }

    public void setOrganizationJobs(List<AccountOrgJob> organizationJobs) {
        this.organizationJobs = organizationJobs;
    }

    public boolean isStudent() {
        return AcountTypeFlag.student.getId() == this.typeFlag;
    }

    public boolean isTeacher() {
        return AcountTypeFlag.teacher.getId() == (this.typeFlag);
    }

    public boolean isParent() {
        return AcountTypeFlag.parent.getId() == (this.typeFlag);
    }
}