package com.njpes.www.entity.baseinfo;

import java.io.Serializable;

public class AccountOrgJob implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = -2456483947733169866L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_org_job.id
     *
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_org_job.user_id
     *
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_org_job.org_id
     *
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_org_job.job_id
     *
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    private Long jobId;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_org_job.id
     *
     * @return the value of user_org_job.id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_org_job.id
     *
     * @param id
     *            the value for user_org_job.id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_org_job.user_id
     *
     * @return the value of user_org_job.user_id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_org_job.user_id
     *
     * @param userId
     *            the value for user_org_job.user_id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_org_job.org_id
     *
     * @return the value of user_org_job.org_id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_org_job.org_id
     *
     * @param orgId
     *            the value for user_org_job.org_id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_org_job.job_id
     *
     * @return the value of user_org_job.job_id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_org_job.job_id
     *
     * @param jobId
     *            the value for user_org_job.job_id
     * @mbggenerated Fri Mar 27 22:34:11 CST 2015
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }
}