package com.njpes.www.entity.baseinfo;

public class GraduatingClass {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column graduatingclass.id
     *
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column graduatingclass.studentid
     *
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    private Long studentid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column graduatingclass.bjid
     *
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    private Integer bjid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column graduatingclass.graduationyear
     *
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    private String graduationyear;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column graduatingclass.id
     *
     * @return the value of graduatingclass.id
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column graduatingclass.id
     *
     * @param id
     *            the value for graduatingclass.id
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column graduatingclass.studentid
     *
     * @return the value of graduatingclass.studentid
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public Long getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column graduatingclass.studentid
     *
     * @param studentid
     *            the value for graduatingclass.studentid
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public void setStudentid(Long studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column graduatingclass.bjid
     *
     * @return the value of graduatingclass.bjid
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public Integer getBjid() {
        return bjid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column graduatingclass.bjid
     *
     * @param bjid
     *            the value for graduatingclass.bjid
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public void setBjid(Integer bjid) {
        this.bjid = bjid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column graduatingclass.graduationyear
     *
     * @return the value of graduatingclass.graduationyear
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public String getGraduationyear() {
        return graduationyear;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column graduatingclass.graduationyear
     *
     * @param graduationyear
     *            the value for graduatingclass.graduationyear
     * @mbggenerated Mon Nov 14 00:07:37 CST 2016
     */
    public void setGraduationyear(String graduationyear) {
        this.graduationyear = graduationyear;
    }
}