package com.njpes.www.entity.baseinfo;

import java.io.Serializable;

public class Job implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job.id
     *
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job.job_code
     *
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    private String jobCode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job.job_name
     *
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job.parent_id
     *
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job.parent_ids
     *
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    private String parentIds;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job.job_sort
     *
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    private Integer jobSort;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column job.is_show
     *
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    private String isShow;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job.id
     *
     * @return the value of job.id
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job.id
     *
     * @param id
     *            the value for job.id
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job.job_code
     *
     * @return the value of job.job_code
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job.job_code
     *
     * @param jobCode
     *            the value for job.job_code
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job.job_name
     *
     * @return the value of job.job_name
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job.job_name
     *
     * @param jobName
     *            the value for job.job_name
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job.parent_id
     *
     * @return the value of job.parent_id
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job.parent_id
     *
     * @param parentId
     *            the value for job.parent_id
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job.parent_ids
     *
     * @return the value of job.parent_ids
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job.parent_ids
     *
     * @param parentIds
     *            the value for job.parent_ids
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job.job_sort
     *
     * @return the value of job.job_sort
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public Integer getJobSort() {
        return jobSort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job.job_sort
     *
     * @param jobSort
     *            the value for job.job_sort
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public void setJobSort(Integer jobSort) {
        this.jobSort = jobSort;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column job.is_show
     *
     * @return the value of job.is_show
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column job.is_show
     *
     * @param isShow
     *            the value for job.is_show
     * @mbggenerated Sat Mar 21 22:55:16 CST 2015
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }
}