package com.njpes.www.entity.baseinfo;

import java.io.Serializable;

public class Permission implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column permission.id
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column permission.perm_name
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    private String permName;
    private String perm_name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column permission.permission
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column permission.perm_desc
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    private String permDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column permission.is_show
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    private String isShow;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column permission.id
     *
     * @return the value of permission.id
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column permission.id
     *
     * @param id
     *            the value for permission.id
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column permission.perm_name
     *
     * @return the value of permission.perm_name
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public String getPermName() {
        return permName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column permission.perm_name
     *
     * @param permName
     *            the value for permission.perm_name
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public void setPermName(String permName) {
        this.permName = permName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column permission.permission
     *
     * @return the value of permission.permission
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column permission.permission
     *
     * @param permission
     *            the value for permission.permission
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column permission.perm_desc
     *
     * @return the value of permission.perm_desc
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public String getPermDesc() {
        return permDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column permission.perm_desc
     *
     * @param permDesc
     *            the value for permission.perm_desc
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public void setPermDesc(String permDesc) {
        this.permDesc = permDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column permission.is_show
     *
     * @return the value of permission.is_show
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column permission.is_show
     *
     * @param isShow
     *            the value for permission.is_show
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    public String getPerm_name() {
        return perm_name;
    }

    public void setPerm_name(String perm_name) {
        this.perm_name = perm_name;
    }

}