package com.njpes.www.entity.baseinfo;

import java.io.Serializable;
import java.util.List;

public class Role implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 8608197473963936923L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column role.id
     *
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column role.role_name
     *
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column role.role 角色标示，系统中使用的唯一名称
     * 
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column role.role_desc
     *
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column role.is_show
     *
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    private String isShow;

    /**
     * 角色对应的资源和权限列表，有可能资源是多个，因此在获取资源时候要进行筛选
     */
    private List<RoleResourcePermission> resourcePermissions;

    private int org_level;
    private String orgLevelName;
    private int role_level;
    private String roleLevelName;

    private String roleOrg;

    private String isadmin;

    private String systemlevel;

    private String roletypeflag;

    public String getRoletypeflag() {
        return roletypeflag;
    }

    public void setRoletypeflag(String roletypeflag) {
        this.roletypeflag = roletypeflag;
    }

    public String getSystemlevel() {
        return systemlevel;
    }

    public void setSystemlevel(String systemlevel) {
        this.systemlevel = systemlevel;
    }

    public String getIsadmin() {
        return isadmin;
    }

    public void setIsadmin(String isadmin) {
        this.isadmin = isadmin;
    }

    public String getRoleOrg() {
        return roleOrg;
    }

    public void setRoleOrg(String roleOrg) {
        this.roleOrg = roleOrg;
    }

    public int getOrg_level() {
        return org_level;
    }

    public void setOrg_level(int org_level) {
        this.org_level = org_level;
    }

    public String getOrgLevelName() {
        return orgLevelName;
    }

    public void setOrgLevelName(String orgLevelName) {
        this.orgLevelName = orgLevelName;
    }

    public int getRole_level() {
        return role_level;
    }

    public void setRole_level(int role_level) {
        this.role_level = role_level;
    }

    public String getRoleLevelName() {
        return roleLevelName;
    }

    public void setRoleLevelName(String roleLevelName) {
        this.roleLevelName = roleLevelName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column role.id
     *
     * @return the value of role.id
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column role.id
     *
     * @param id
     *            the value for role.id
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column role.role_name
     *
     * @return the value of role.role_name
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column role.role_name
     *
     * @param roleName
     *            the value for role.role_name
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column role.role
     *
     * @return the value of role.role
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column role.role
     *
     * @param role
     *            the value for role.role
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column role.role_desc
     *
     * @return the value of role.role_desc
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column role.role_desc
     *
     * @param roleDesc
     *            the value for role.role_desc
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column role.is_show
     *
     * @return the value of role.is_show
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column role.is_show
     *
     * @param isShow
     *            the value for role.is_show
     * @mbggenerated Sat Mar 21 22:53:17 CST 2015
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * @return the resourcePermissions
     */
    public List<RoleResourcePermission> getResourcePermissions() {
        return resourcePermissions;
    }

    /**
     * @param resourcePermissions
     *            the resourcePermissions to set
     */
    public void setResourcePermissions(List<RoleResourcePermission> resourcePermissions) {
        this.resourcePermissions = resourcePermissions;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj instanceof Role) {
            if (this.id.equals(((Role) obj).id)) {
                return true;
            }
            return false;
        }
        return false;
    }

    @Override
    public String toString() {
        return id + roleName + resourcePermissions.toString();
    }
}