package com.njpes.www.entity.baseinfo;

public class StudentWithBLOBs extends Student {
    /**
     * 照片 This field was generated by MyBatis Generator. This field corresponds
     * to the database column student.zp
     *
     * @mbggenerated Fri May 01 17:08:16 CST 2015
     */
    private byte[] zp;

    /**
     * 特长 This field was generated by MyBatis Generator. This field corresponds
     * to the database column student.tc
     *
     * @mbggenerated Fri May 01 17:08:16 CST 2015
     */
    private String tc;

    private String bjxx;

    public String getBjxx() {
        return bjxx;
    }

    public void setBjxx(String bjxx) {
        this.bjxx = bjxx;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column student.zp
     *
     * @return the value of student.zp
     * @mbggenerated Fri May 01 17:08:16 CST 2015
     */
    public byte[] getZp() {
        return zp;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column student.zp
     *
     * @param zp
     *            the value for student.zp
     * @mbggenerated Fri May 01 17:08:16 CST 2015
     */
    public void setZp(byte[] zp) {
        this.zp = zp;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column student.tc
     *
     * @return the value of student.tc
     * @mbggenerated Fri May 01 17:08:16 CST 2015
     */
    public String getTc() {
        return tc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column student.tc
     *
     * @param tc
     *            the value for student.tc
     * @mbggenerated Fri May 01 17:08:16 CST 2015
     */
    public void setTc(String tc) {
        this.tc = tc;
    }

     public void setBackGrandByStr(){
     setBackGrand(this.bjxx);
     }
    private String gradeid;
    private String classid;
    private String username;

    public String getGradeid() {
        return gradeid;
    }

    public void setGradeid(String gradeid) {
        this.gradeid = gradeid;
    }

    public String getClassid() {
        return classid;
    }

    public void setClassid(String classid) {
        this.classid = classid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

}