package com.njpes.www.entity.baseinfo;

import java.io.Serializable;
import java.util.List;

import org.apache.commons.lang.math.NumberUtils;

import com.njpes.www.constant.Constants;

public class Teacher extends SchoolUser implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 8663069378464374716L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column teacher.id
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // private Long id;

    /**
     * 工号 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.gh
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String gh;
    /**
     * 学校名称
     */
    private String xxmc;

    private Long schoolid;

    public Long getSchoolid() {
        return schoolid;
    }

    public void setSchoolid(Long schoolid) {
        this.schoolid = schoolid;
    }

    /**
     * 角色名称
     */
    private String rolename;
    /**
     * 姓名 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.xm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // private String xm;

    /**
     * 英文姓名 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.ywxm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String ywxm;

    /**
     * 姓名拼音 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.xmpy
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String xmpy;

    /**
     * 曾用名 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.cym
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String cym;

    /**
     * 性别码 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.xbm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // private String xbm;

    /**
     * 出生日期 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.csrq
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // private String csrq;

    /**
     * 出生地码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.csdm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String csdm;

    /**
     * 籍贯 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.jg
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String jg;

    /**
     * 民族码 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.mzm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String mzm;

    /**
     * 国籍/地区码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.gjdqm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String gjdqm;

    /**
     * 身份证件类型码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.sfzjlxm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String sfzjlxm;

    /**
     * 身份证件号 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.sfzjh
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String sfzjh;

    /**
     * 婚姻状况码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.hyzkm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String hyzkm;

    /**
     * 港澳台侨外码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.gatqwm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String gatqwm;

    /**
     * 政治面貌码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.zzmmm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String zzmmm;

    /**
     * 健康状况码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.jkzkm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String jkzkm;

    /**
     * 信仰宗教码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.xyzjm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String xyzjm;

    /**
     * 血型码 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.xxm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String xxm;

    /**
     * 身份证件有效期 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.sfzjyxq
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String sfzjyxq;

    /**
     * 机构号 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.jgh
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String jgh;

    /**
     * 家庭住址 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.jtzz
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String jtzz;

    /**
     * 现住址 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.xzz
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String xzz;

    /**
     * 户口所在地 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.hkszd
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String hkszd;

    /**
     * 户口性质码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.hkxzm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String hkxzm;

    /**
     * 学历码 This field was generated by MyBatis Generator. This field corresponds
     * to the database column teacher.xlm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String xlm;

    /**
     * 参加工作年月 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.gzny
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String gzny;

    /**
     * 来校年月 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.lxny
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String lxny;

    /**
     * 从教年月 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.cjny
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String cjny;

    /**
     * 编制类别码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.bzlbm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String bzlbm;

    /**
     * 档案编号 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.dabh
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String dabh;

    /**
     * 通信地址 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.txdz
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String txdz;

    /**
     * 联系电话 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.lxdh
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String lxdh;

    /**
     * 邮政编码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.yzbm
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String yzbm;

    /**
     * 电子信箱 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.dzxx
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String dzxx;

    /**
     * 主页地址 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.zydz
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String zydz;

    /**
     * 岗位职业码 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.gwzym
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String gwzym;

    /**
     * 主要任课学段 This field was generated by MyBatis Generator. This field
     * corresponds to the database column teacher.zyrkxd
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    private String zyrkxd;

    private Long accountId;

    // private String bjxx;

    private String sexname;

    private List<Auth> teacherAuthList;

    public String getSexname() {
        return sexname;
    }

    public void setSexname(String sexname) {
        this.sexname = sexname;
    }

    public long getOrgid() {
        return teacherAuthList.get(0).getOrgId();
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    // public String getBjxx() {
    // return bjxx;
    // }

    // public void setBjxx(String bjxx) {
    // this.bjxx = bjxx;
    // }

    public List<Auth> getTeacherAuthList() {
        return teacherAuthList;
    }

    public void setTeacherAuthList(List<Auth> teacherAuthList) {
        this.teacherAuthList = teacherAuthList;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.id
     *
     * @return the value of teacher.id
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public Long getId() {
    // return id;
    // }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.id
     *
     * @param id
     *            the value for teacher.id
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public void setId(Long id) {
    // this.id = id;
    // }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.gh
     *
     * @return the value of teacher.gh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getGh() {
        return gh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.gh
     *
     * @param gh
     *            the value for teacher.gh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setGh(String gh) {
        this.gh = gh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.xm
     *
     * @return the value of teacher.xm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public String getXm() {
    // return xm;
    // }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.xm
     *
     * @param xm
     *            the value for teacher.xm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public void setXm(String xm) {
    // this.xm = xm;
    // }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.ywxm
     *
     * @return the value of teacher.ywxm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getYwxm() {
        return ywxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.ywxm
     *
     * @param ywxm
     *            the value for teacher.ywxm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setYwxm(String ywxm) {
        this.ywxm = ywxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.xmpy
     *
     * @return the value of teacher.xmpy
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getXmpy() {
        return xmpy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.xmpy
     *
     * @param xmpy
     *            the value for teacher.xmpy
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setXmpy(String xmpy) {
        this.xmpy = xmpy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.cym
     *
     * @return the value of teacher.cym
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getCym() {
        return cym;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.cym
     *
     * @param cym
     *            the value for teacher.cym
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setCym(String cym) {
        this.cym = cym;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.xbm
     *
     * @return the value of teacher.xbm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public String getXbm() {
    // return xbm;
    // }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.xbm
     *
     * @param xbm
     *            the value for teacher.xbm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public void setXbm(String xbm) {
    // this.xbm = xbm;
    // }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.csrq
     *
     * @return the value of teacher.csrq
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public String getCsrq() {
    // return csrq;
    // }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.csrq
     *
     * @param csrq
     *            the value for teacher.csrq
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    // public void setCsrq(String csrq) {
    // this.csrq = csrq;
    // }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.csdm
     *
     * @return the value of teacher.csdm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getCsdm() {
        return csdm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.csdm
     *
     * @param csdm
     *            the value for teacher.csdm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setCsdm(String csdm) {
        this.csdm = csdm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.jg
     *
     * @return the value of teacher.jg
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.jg
     *
     * @param jg
     *            the value for teacher.jg
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setJg(String jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.mzm
     *
     * @return the value of teacher.mzm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getMzm() {
        return mzm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.mzm
     *
     * @param mzm
     *            the value for teacher.mzm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setMzm(String mzm) {
        this.mzm = mzm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.gjdqm
     *
     * @return the value of teacher.gjdqm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getGjdqm() {
        return gjdqm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.gjdqm
     *
     * @param gjdqm
     *            the value for teacher.gjdqm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setGjdqm(String gjdqm) {
        this.gjdqm = gjdqm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.sfzjlxm
     *
     * @return the value of teacher.sfzjlxm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getSfzjlxm() {
        return sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.sfzjlxm
     *
     * @param sfzjlxm
     *            the value for teacher.sfzjlxm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setSfzjlxm(String sfzjlxm) {
        this.sfzjlxm = sfzjlxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.sfzjh
     *
     * @return the value of teacher.sfzjh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getSfzjh() {
        return sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.sfzjh
     *
     * @param sfzjh
     *            the value for teacher.sfzjh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setSfzjh(String sfzjh) {
        this.sfzjh = sfzjh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.hyzkm
     *
     * @return the value of teacher.hyzkm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getHyzkm() {
        return hyzkm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.hyzkm
     *
     * @param hyzkm
     *            the value for teacher.hyzkm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setHyzkm(String hyzkm) {
        this.hyzkm = hyzkm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.gatqwm
     *
     * @return the value of teacher.gatqwm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getGatqwm() {
        return gatqwm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.gatqwm
     *
     * @param gatqwm
     *            the value for teacher.gatqwm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setGatqwm(String gatqwm) {
        this.gatqwm = gatqwm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.zzmmm
     *
     * @return the value of teacher.zzmmm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getZzmmm() {
        return zzmmm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.zzmmm
     *
     * @param zzmmm
     *            the value for teacher.zzmmm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setZzmmm(String zzmmm) {
        this.zzmmm = zzmmm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.jkzkm
     *
     * @return the value of teacher.jkzkm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getJkzkm() {
        return jkzkm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.jkzkm
     *
     * @param jkzkm
     *            the value for teacher.jkzkm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setJkzkm(String jkzkm) {
        this.jkzkm = jkzkm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.xyzjm
     *
     * @return the value of teacher.xyzjm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getXyzjm() {
        return xyzjm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.xyzjm
     *
     * @param xyzjm
     *            the value for teacher.xyzjm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setXyzjm(String xyzjm) {
        this.xyzjm = xyzjm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.xxm
     *
     * @return the value of teacher.xxm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getXxm() {
        return xxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.xxm
     *
     * @param xxm
     *            the value for teacher.xxm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setXxm(String xxm) {
        this.xxm = xxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.sfzjyxq
     *
     * @return the value of teacher.sfzjyxq
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getSfzjyxq() {
        return sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.sfzjyxq
     *
     * @param sfzjyxq
     *            the value for teacher.sfzjyxq
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setSfzjyxq(String sfzjyxq) {
        this.sfzjyxq = sfzjyxq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.jgh
     *
     * @return the value of teacher.jgh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getJgh() {
        return jgh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.jgh
     *
     * @param jgh
     *            the value for teacher.jgh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setJgh(String jgh) {
        this.jgh = jgh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.jtzz
     *
     * @return the value of teacher.jtzz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getJtzz() {
        return jtzz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.jtzz
     *
     * @param jtzz
     *            the value for teacher.jtzz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setJtzz(String jtzz) {
        this.jtzz = jtzz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.xzz
     *
     * @return the value of teacher.xzz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getXzz() {
        return xzz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.xzz
     *
     * @param xzz
     *            the value for teacher.xzz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setXzz(String xzz) {
        this.xzz = xzz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.hkszd
     *
     * @return the value of teacher.hkszd
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getHkszd() {
        return hkszd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.hkszd
     *
     * @param hkszd
     *            the value for teacher.hkszd
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setHkszd(String hkszd) {
        this.hkszd = hkszd;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.hkxzm
     *
     * @return the value of teacher.hkxzm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getHkxzm() {
        return hkxzm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.hkxzm
     *
     * @param hkxzm
     *            the value for teacher.hkxzm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setHkxzm(String hkxzm) {
        this.hkxzm = hkxzm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.xlm
     *
     * @return the value of teacher.xlm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getXlm() {
        return xlm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.xlm
     *
     * @param xlm
     *            the value for teacher.xlm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setXlm(String xlm) {
        this.xlm = xlm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.gzny
     *
     * @return the value of teacher.gzny
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getGzny() {
        return gzny;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.gzny
     *
     * @param gzny
     *            the value for teacher.gzny
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setGzny(String gzny) {
        this.gzny = gzny;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.lxny
     *
     * @return the value of teacher.lxny
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getLxny() {
        return lxny;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.lxny
     *
     * @param lxny
     *            the value for teacher.lxny
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setLxny(String lxny) {
        this.lxny = lxny;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.cjny
     *
     * @return the value of teacher.cjny
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getCjny() {
        return cjny;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.cjny
     *
     * @param cjny
     *            the value for teacher.cjny
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setCjny(String cjny) {
        this.cjny = cjny;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.bzlbm
     *
     * @return the value of teacher.bzlbm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getBzlbm() {
        return bzlbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.bzlbm
     *
     * @param bzlbm
     *            the value for teacher.bzlbm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setBzlbm(String bzlbm) {
        this.bzlbm = bzlbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.dabh
     *
     * @return the value of teacher.dabh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getDabh() {
        return dabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.dabh
     *
     * @param dabh
     *            the value for teacher.dabh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setDabh(String dabh) {
        this.dabh = dabh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.txdz
     *
     * @return the value of teacher.txdz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getTxdz() {
        return txdz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.txdz
     *
     * @param txdz
     *            the value for teacher.txdz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setTxdz(String txdz) {
        this.txdz = txdz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.lxdh
     *
     * @return the value of teacher.lxdh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.lxdh
     *
     * @param lxdh
     *            the value for teacher.lxdh
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.yzbm
     *
     * @return the value of teacher.yzbm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.yzbm
     *
     * @param yzbm
     *            the value for teacher.yzbm
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.dzxx
     *
     * @return the value of teacher.dzxx
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getDzxx() {
        return dzxx;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.dzxx
     *
     * @param dzxx
     *            the value for teacher.dzxx
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setDzxx(String dzxx) {
        this.dzxx = dzxx;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.zydz
     *
     * @return the value of teacher.zydz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getZydz() {
        return zydz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.zydz
     *
     * @param zydz
     *            the value for teacher.zydz
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setZydz(String zydz) {
        this.zydz = zydz;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.gwzym
     *
     * @return the value of teacher.gwzym
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getGwzym() {
        return gwzym;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.gwzym
     *
     * @param gwzym
     *            the value for teacher.gwzym
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setGwzym(String gwzym) {
        this.gwzym = gwzym;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column teacher.zyrkxd
     *
     * @return the value of teacher.zyrkxd
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public String getZyrkxd() {
        return zyrkxd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column teacher.zyrkxd
     *
     * @param zyrkxd
     *            the value for teacher.zyrkxd
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    public void setZyrkxd(String zyrkxd) {
        this.zyrkxd = zyrkxd;
    }

    public String getXxmc() {
        return xxmc;
    }

    public void setXxmc(String xxmc) {
        this.xxmc = xxmc;
    }

    public String getRolename() {
        return rolename;
    }

    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    public String getGenderWord() {
        return Constants.G_DESC[NumberUtils.toInt(getXbm())];
    }

    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public int[] getCateIds() {
        return Constants.TCH_PROP_NUMS;
    }

    @Override
    public Object getAttrObject() {
        // TODO Auto-generated method stub
        return null;
    }

    // ------------------------------------------
    private Integer dogid;
    private String vendorID = "";
    private String challenge;
    private String Factor;
    private String authCode;
    private String isdogid;

    public String getIsdogid() {
        return isdogid;
    }

    public void setIsdogid(String isdogid) {
        this.isdogid = isdogid;
    }

    public Integer getDogid() {
        return dogid;
    }

    public void setDogid(Integer dogid) {
        this.dogid = dogid;
    }

    public String getVendorID() {
        return vendorID;
    }

    public void setVendorID(String vendorID) {
        this.vendorID = vendorID;
    }

    public String getChallenge() {
        return challenge;
    }

    public void setChallenge(String challenge) {
        this.challenge = challenge;
    }

    public String getFactor() {
        return Factor;
    }

    public void setFactor(String factor) {
        Factor = factor;
    }

    public String getAuthCode() {
        return authCode;
    }

    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

}