package com.njpes.www.entity.baseinfo;

public class UserResPerm {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_res_perm.id
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_res_perm.user_id
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    private Long userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_res_perm.res_id
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    private Long resId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_res_perm.perm_ids
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    private String permIds;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_res_perm.auth_type
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    private String authType;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_res_perm.orgtype
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    private String orgtype;

    private Resource resource;

    public Resource getResource() {
        return resource;
    }

    public void setResource(Resource resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_res_perm.id
     * 
     * @return the value of user_res_perm.id
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_res_perm.id
     * 
     * @param id
     *            the value for user_res_perm.id
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_res_perm.user_id
     * 
     * @return the value of user_res_perm.user_id
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_res_perm.user_id
     * 
     * @param userId
     *            the value for user_res_perm.user_id
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_res_perm.res_id
     * 
     * @return the value of user_res_perm.res_id
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public Long getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_res_perm.res_id
     * 
     * @param resId
     *            the value for user_res_perm.res_id
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public void setResId(Long resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_res_perm.perm_ids
     * 
     * @return the value of user_res_perm.perm_ids
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public String getPermIds() {
        return permIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_res_perm.perm_ids
     * 
     * @param permIds
     *            the value for user_res_perm.perm_ids
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public void setPermIds(String permIds) {
        this.permIds = permIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_res_perm.auth_type
     * 
     * @return the value of user_res_perm.auth_type
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public String getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_res_perm.auth_type
     * 
     * @param authType
     *            the value for user_res_perm.auth_type
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public void setAuthType(String authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_res_perm.orgtype
     * 
     * @return the value of user_res_perm.orgtype
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public String getOrgtype() {
        return orgtype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_res_perm.orgtype
     * 
     * @param orgtype
     *            the value for user_res_perm.orgtype
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    public void setOrgtype(String orgtype) {
        this.orgtype = orgtype;
    }
}