package com.njpes.www.dao.baseinfo;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.Auth;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table auth
     *
     * @mbggenerated Sat Mar 21 22:49:29 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table auth
     *
     * @mbggenerated Sat Mar 21 22:49:29 CST 2015
     */
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table auth
     *
     * @mbggenerated Sat Mar 21 22:49:29 CST 2015
     */
    int insertSelective(Auth record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table auth
     *
     * @mbggenerated Sat Mar 21 22:49:29 CST 2015
     */
    Auth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table auth
     *
     * @mbggenerated Sat Mar 21 22:49:29 CST 2015
     */
    int updateByPrimaryKeySelective(Auth record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table auth
     *
     * @mbggenerated Sat Mar 21 22:49:29 CST 2015
     */
    int updateByPrimaryKey(Auth record);

    /**
     * 根据用户id查找用户具有的授权信息
     * 
     * @param userId
     *            用户id
     * @author 赵忠诚
     */
    List<Auth> selectByUserId(@Param("userId") Long userId, @Param("logintype") String logintype);

    /**
     * 根据组织机构id查找授权信息
     * 
     * @param groupId
     *            用户id
     * @author 赵忠诚
     */
    List<Auth> selectByGroupId(@Param("userId") Long groupId);

    List<Auth> selectByOrgIdAndJobId(@Param("orgId") Long orgId, @Param("jobId") Long jobId);

    List<Auth> selectByUGOJIds(@Param("userId") Long userId, @Param("groupIds") Set<Long> groupIds,
            @Param("orgIds") Set<Long> orgIds, @Param("jobIds") Set<Long> jobIds,
            @Param("org_jobIds") Set<Long[]> organizationJobIds);

    int deleteByUserId(@Param("userId") long userId);

    void insertBatch(List<Auth> auths);

}