package com.njpes.www.dao.baseinfo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.organization.Ecpsychicteam;

public interface EcpsychicteamMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ec_psychicteam
     *
     * @mbggenerated Sat May 09 22:29:22 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ec_psychicteam
     *
     * @mbggenerated Sat May 09 22:29:22 CST 2015
     */
    int insert(Ecpsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ec_psychicteam
     *
     * @mbggenerated Sat May 09 22:29:22 CST 2015
     */
    int insertSelective(Ecpsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ec_psychicteam
     *
     * @mbggenerated Sat May 09 22:29:22 CST 2015
     */
    Ecpsychicteam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ec_psychicteam
     *
     * @mbggenerated Sat May 09 22:29:22 CST 2015
     */
    int updateByPrimaryKeySelective(Ecpsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ec_psychicteam
     *
     * @mbggenerated Sat May 09 22:29:22 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Ecpsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ec_psychicteam
     *
     * @mbggenerated Sat May 09 22:29:22 CST 2015
     */
    int updateByPrimaryKey(Ecpsychicteam record);

    /**
     * 根据组织机构id获取心理工作team信息
     * 
     * @param 教委id
     * @return 列表
     * @author 赵忠诚
     */
    public List<Ecpsychicteam> getTeamsByOrgid(@Param("ecid") Long ecid);
}