package com.njpes.www.dao.baseinfo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.EcUser;
import com.njpes.www.entity.baseinfo.EcUserWithBLOBs;
import com.njpes.www.entity.baseinfo.organization.Organization;
import com.njpes.www.utils.PageParameter;

public interface EcUserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ecuser
     *
     * @mbggenerated Wed Nov 04 23:01:44 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ecuser
     *
     * @mbggenerated Wed Nov 04 23:01:44 CST 2015
     */
    int insert(EcUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ecuser
     *
     * @mbggenerated Wed Nov 04 23:01:44 CST 2015
     */
    int insertSelective(EcUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ecuser
     *
     * @mbggenerated Wed Nov 04 23:01:44 CST 2015
     */

    // 史斌增加批量插入
    int insertBatch(List<EcUserWithBLOBs> ecusers);

    // 史斌增加批量更新
    int updateBatch(List<EcUserWithBLOBs> ecusers);

    EcUserWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ecuser
     *
     * @mbggenerated Wed Nov 04 23:01:44 CST 2015
     */
    int updateByPrimaryKeySelective(EcUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ecuser
     *
     * @mbggenerated Wed Nov 04 23:01:44 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(EcUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ecuser
     *
     * @mbggenerated Wed Nov 04 23:01:44 CST 2015
     */
    int updateByPrimaryKey(EcUser record);

    public List<EcUserWithBLOBs> selectEcUsersByParentOrgidByPage(@Param("ecuser") EcUserWithBLOBs ecuser,
            @Param("parentorgid") long parentorgid, @Param("queryOrgEntity") Organization queryOrgEntity,
            @Param("page") PageParameter page);

    public List<EcUserWithBLOBs> selectEcUsersByParentOrgid(@Param("parentorgid") long parentorgid,
            @Param("queryOrgEntity") Organization queryOrgEntity);

    EcUserWithBLOBs selectByAccountId(Long id);
}