package com.njpes.www.dao.baseinfo;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.organization.Grade;
import com.njpes.www.entity.scaletoollib.ScaleGrades;

public interface GradeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table grade
     * 
     * @mbggenerated Mon May 25 23:46:40 CST 2015
     */
    Grade selectByPrimaryKey(Integer id);

    int insertScaleGrades(ScaleGrades scalegrades);

    /**
     * 根据名称查询年级组的id
     * 
     * @author shibin
     * @param groupname
     * @return
     */
    Integer selectGradeGroupIdByName(String groupname);

    /**
     * 根据名称查询年级的id
     * 
     * @author shibin
     * @param groupname
     * @return
     */
    Integer selectGradeIdByName(String gradename);

    /**
     * @author 赵忠诚
     */

    public List<Grade> getGradeBySchoolGroupXZ(@Param("school") int s, @Param("xz") int xz);

    /**
     * 获得学校的最大小学学制，最大初中学制，最大高中学制
     * 
     * @param xxxz
     * @param czxz
     * @param gzxz
     * @return
     */
    public Map<String, BigDecimal> getMaxXZinSchools(@Param("schools") List<String> schools);

    /**
     * 根据学校id列表获得年级列表
     * 
     * @param schools
     * @author shibin
     * @return
     */
    public List<Grade> getGradeinSchools(@Param("xxxz") String xxxz, @Param("czxz") String czxz,
            @Param("gzxz") String gzxz);
}