package com.njpes.www.dao.baseinfo;

import com.njpes.www.entity.baseinfo.Group;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table group
     *
     * @mbggenerated Sat Mar 21 22:51:18 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table group
     *
     * @mbggenerated Sat Mar 21 22:51:18 CST 2015
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table group
     *
     * @mbggenerated Sat Mar 21 22:51:18 CST 2015
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table group
     *
     * @mbggenerated Sat Mar 21 22:51:18 CST 2015
     */
    Group selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table group
     *
     * @mbggenerated Sat Mar 21 22:51:18 CST 2015
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table group
     *
     * @mbggenerated Sat Mar 21 22:51:18 CST 2015
     */
    int updateByPrimaryKey(Group record);

}