package com.njpes.www.dao.baseinfo;

import java.util.List;

import com.njpes.www.entity.baseinfo.Permission;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table permission
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table permission
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table permission
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table permission
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table permission
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table permission
     *
     * @mbggenerated Sat Mar 21 22:54:04 CST 2015
     */
    int updateByPrimaryKey(Permission record);

    List<Permission> selectAllPermissions();

}