package com.njpes.www.dao.baseinfo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.organization.SchoolPsychicteam;

public interface SchoolPsychicteamMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table school_psychicteam
     *
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table school_psychicteam
     *
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    int insert(SchoolPsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table school_psychicteam
     *
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    int insertSelective(SchoolPsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table school_psychicteam
     *
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    SchoolPsychicteam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table school_psychicteam
     *
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    int updateByPrimaryKeySelective(SchoolPsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table school_psychicteam
     *
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SchoolPsychicteam record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table school_psychicteam
     *
     * @mbggenerated Wed Aug 12 22:45:05 CST 2015
     */
    int updateByPrimaryKey(SchoolPsychicteam record);

    /**
     * 根据组织机构id获取心理工作team信息
     * 
     * @param 教委id
     * @return 列表
     * @author 赵忠诚
     */
    public List<SchoolPsychicteam> getTeamsByOrgid(@Param("schoolid") Long schoolid);
}