package com.njpes.www.dao.baseinfo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.Syslog;
import com.njpes.www.entity.baseinfo.SyslogFilterParam;
import com.njpes.www.utils.PageParameter;

public interface SyslogMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table syslog
     *
     * @mbggenerated Sat Apr 11 15:06:39 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table syslog
     *
     * @mbggenerated Sat Apr 11 15:06:39 CST 2015
     */
    int insert(Syslog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table syslog
     *
     * @mbggenerated Sat Apr 11 15:06:39 CST 2015
     */
    int insertSelective(Syslog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table syslog
     *
     * @mbggenerated Sat Apr 11 15:06:39 CST 2015
     */
    Syslog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table syslog
     *
     * @mbggenerated Sat Apr 11 15:06:39 CST 2015
     */
    int updateByPrimaryKeySelective(Syslog record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table syslog
     *
     * @mbggenerated Sat Apr 11 15:06:39 CST 2015
     */
    int updateByPrimaryKey(Syslog record);

    // 获取相关的日志
    public List<Syslog> queryPageSyslogEntity(@Param("syslogFilterParam") SyslogFilterParam syslogFilterParam);

    public List<Syslog> queryPageSyslogByPage(@Param("page") PageParameter page,
            @Param("syslogFilterParam") SyslogFilterParam syslogFilterParam);

}