package com.njpes.www.dao.baseinfo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.AccountDetail;
import com.njpes.www.entity.baseinfo.Teacher;
import com.njpes.www.entity.baseinfo.TeacherQueryParam;
import com.njpes.www.entity.baseinfo.TeacherWithBLOBs;
import com.njpes.www.entity.scaletoollib.StatHuman;
import com.njpes.www.entity.scaletoollib.StatScope;
import com.njpes.www.utils.PageParameter;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table teacher
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table teacher
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    int insert(TeacherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table teacher
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    int insertSelective(TeacherWithBLOBs record);

    // 史斌增加批量插入
    int insertBatch(List<TeacherWithBLOBs> teachers);

    // 史斌增加批量更新
    int updateBatch(List<TeacherWithBLOBs> teachers);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table teacher
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    TeacherWithBLOBs selectByPrimaryKey(Long id);

    TeacherWithBLOBs getTeacherByAccountId(Long id);

    TeacherWithBLOBs getTeacherByIdentify(@Param("sfzjh") String sfzjh);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table teacher
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    int updateByPrimaryKeySelective(TeacherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table teacher
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(TeacherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table teacher
     *
     * @mbggenerated Fri May 01 23:24:34 CST 2015
     */
    int updateByPrimaryKey(Teacher record);

    int updateTeacherBjxx(TeacherWithBLOBs record);

    AccountDetail selectByAccountId(int accountId);

    void updateByAccountId(AccountDetail accountDetail);

    List<TeacherWithBLOBs> getTeachers(Map<String, Object> params);

    /**
     * 学校里所有老师
     * 
     * @author shibin
     * @param params
     * @return
     */
    List<TeacherWithBLOBs> getTeachersInSchool(@Param("jgh") String orgCode);

    /**
     * @author 赵忠诚
     */
    List<Teacher> getTeachersByPage(@Param("teacher") TeacherQueryParam teacher, @Param("orgid") long schoolorgid,
            @Param("page") PageParameter page, @Param("excludesids") List<Long> excludesids);

    List<Teacher> getAdminTeachersByPage(@Param("teacher") TeacherQueryParam teacher, @Param("orgid") long schoolorgid,
            @Param("parentorgid") long parentorgid, @Param("page") PageParameter page);

    /**
     * @author 赵忠诚
     */
    List<Teacher> getAllTeachers(@Param("teacher") TeacherQueryParam teacher, @Param("orgid") long schoolorgid,
            @Param("excludesids") List<Long> excludesids);

    /**
     * @author 赵忠诚
     */
    List<Teacher> getTeachersInSchoolByType(@Param("id") long schoolid, @Param("type") int type);

    List<Teacher> getPsychologyTeacherInSchool(@Param("id") long schoolid);

    /**
     * @author 赵忠诚
     */
    List<Teacher> getTeachersByids(@Param("ids") List<Long> ids);

    List<Teacher> getTeachers(@Param("teacherRole") String teacherRole, @Param("orgid") String orgid);

    List<Map> getBasicTeachers(Map param);

    List<Integer> getBzrId(Map param);// 获得班主任id号

    List<StatHuman> getTeachersByStatscope(@Param("scope") StatScope scope);
}