package com.njpes.www.dao.baseinfo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.njpes.www.entity.baseinfo.UserResPerm;

public interface UserResPermMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_res_perm
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_res_perm
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    int insert(UserResPerm record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_res_perm
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    int insertSelective(UserResPerm record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_res_perm
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    UserResPerm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_res_perm
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    int updateByPrimaryKeySelective(UserResPerm record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user_res_perm
     * 
     * @mbggenerated Sun Mar 20 23:22:54 CST 2016
     */
    int updateByPrimaryKey(UserResPerm record);

    List<UserResPerm> selectResPermsByUser(@Param("userId") Long userId, @Param("logintype") String logintype);

    int deleteResPermsByUserId(@Param("userId") Long userId, @Param("logintype") String logintype);

    int insertList(@Param("list") List<UserResPerm> records);
}